# Generated by Django 6.0.3 on 2026-03-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrespondenz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefvorlage',
            name='default_absender_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Standard-Absender E-Mail'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='default_absender_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Standard-Absender Name/Firma'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='default_absender_ort',
            field=models.CharField(blank=True, max_length=200, verbose_name='Standard-Absender PLZ/Ort'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='default_absender_strasse',
            field=models.CharField(blank=True, max_length=200, verbose_name='Standard-Absender Strasse'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='default_absender_telefon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Standard-Absender Telefon'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='default_grussformel',
            field=models.CharField(blank=True, max_length=200, verbose_name='Standard-Grussformel'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='default_ort',
            field=models.CharField(blank=True, max_length=100, verbose_name='Standard-Ort (Datum-Zeile)'),
        ),
    ]
