# Generated by Django 6.0.3 on 2026-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrespondenz', '0002_add_vorlage_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefvorlage',
            name='ist_standard',
            field=models.BooleanField(default=False, help_text='Diese Vorlage wird beim Erstellen eines neuen Briefes automatisch vorausgewaehlt.', verbose_name='Standard-Vorlage'),
        ),
    ]
