# Generated by Django 6.0.3 on 2026-03-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrespondenz', '0003_briefvorlage_ist_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefvorlage',
            name='fusszeile_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fusszeile E-Mail'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='fusszeile_firmenname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fusszeile Firmenname'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='fusszeile_internet',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fusszeile Internet'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='fusszeile_telefax',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fusszeile Telefax'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='fusszeile_telefon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fusszeile Telefon'),
        ),
    ]
