# Generated by Django 6.0.3 on 2026-03-09 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farbe', models.CharField(default='#6c757d', max_length=7, verbose_name='Farbe (Hex)')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Dokument-Tag',
                'verbose_name_plural': 'Dokument-Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DokumentKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(blank=True, max_length=500, verbose_name='Beschreibung')),
                ('klasse', models.CharField(choices=[('offen', 'Offen (Volltext)'), ('sensibel', 'Sensibel (verschluesselt)')], default='offen', max_length=10, verbose_name='Dokumentenklasse')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('sortierung', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('elternkategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unterkategorien', to='dms.dokumentkategorie', verbose_name='Elternkategorie')),
            ],
            options={
                'verbose_name': 'Dokumentkategorie',
                'verbose_name_plural': 'Dokumentkategorien',
                'ordering': ['sortierung', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateiname', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('dateityp', models.CharField(max_length=100, verbose_name='MIME-Typ')),
                ('groesse_bytes', models.IntegerField(verbose_name='Dateigroesse (Bytes)')),
                ('titel', models.CharField(max_length=300, verbose_name='Titel')),
                ('klasse', models.CharField(choices=[('offen', 'Offen'), ('sensibel', 'Sensibel')], default='offen', max_length=10, verbose_name='Dokumentenklasse')),
                ('inhalt_roh', models.BinaryField(blank=True, null=True, verbose_name='Inhalt (unkryptiert, Klasse 1)')),
                ('inhalt_verschluesselt', models.BinaryField(blank=True, null=True, verbose_name='Inhalt (AES-256-GCM, Klasse 2)')),
                ('verschluessel_nonce', models.CharField(blank=True, max_length=24, verbose_name='AES-GCM Nonce (Hex)')),
                ('suchvektor', models.TextField(blank=True, editable=False, verbose_name='Suchvektor')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='Gueltig bis')),
                ('paperless_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Paperless-ngx ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_dokumente', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('sichtbar_fuer', models.ManyToManyField(blank=True, related_name='sichtbare_dokumente', to=settings.AUTH_USER_MODEL, verbose_name='Sichtbar fuer')),
                ('kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumente', to='dms.dokumentkategorie', verbose_name='Kategorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='dokumente', to='dms.dokumenttag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='PaperlessImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fehler', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('importiert_am', models.DateTimeField(auto_now_add=True, verbose_name='Importiert am')),
                ('paperless_id', models.IntegerField(unique=True, verbose_name='Paperless-ngx Dokument-ID')),
                ('status', models.CharField(choices=[('ok', 'Erfolgreich'), ('fehler', 'Fehler'), ('uebersprungen', 'Uebersprungen')], default='ok', max_length=20, verbose_name='Status')),
                ('dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paperless_imports', to='dms.dokument', verbose_name='Importiertes Dokument')),
            ],
            options={
                'verbose_name': 'Paperless-Import-Log',
                'verbose_name_plural': 'Paperless-Import-Logs',
                'ordering': ['-importiert_am'],
            },
        ),
        migrations.CreateModel(
            name='ZugriffsProtokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktion', models.CharField(choices=[('download', 'Download'), ('vorschau', 'Vorschau'), ('erstellt', 'Erstellt'), ('geaendert', 'Geaendert')], default='download', max_length=20, verbose_name='Aktion')),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zugriffe', to='dms.dokument', verbose_name='Dokument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dms_zugriffe', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Zugriffs-Protokoll',
                'verbose_name_plural': 'Zugriffs-Protokolle',
                'ordering': ['-zeitpunkt'],
            },
        ),
    ]
