# Generated by Django 6.0.3 on 2026-03-09 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_eigentuemereinheit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokument',
            options={'ordering': ['-erstellt_am'], 'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AlterField(
            model_name='zugriffsprotokoll',
            name='aktion',
            field=models.CharField(choices=[('download', 'Download'), ('vorschau', 'Vorschau'), ('erstellt', 'Erstellt'), ('geaendert', 'Geaendert'), ('zugriff_beantragt', 'Zugriff beantragt'), ('zugriff_genehmigt', 'Zugriff genehmigt'), ('zugriff_abgelehnt', 'Zugriff abgelehnt'), ('zugriff_widerrufen', 'Zugriff widerrufen'), ('onlyoffice_bearbeitet', 'In OnlyOffice bearbeitet'), ('version_wiederhergestellt', 'Version wiederhergestellt')], default='download', max_length=25, verbose_name='Aktion'),
        ),
        migrations.CreateModel(
            name='DokumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateiname', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('groesse_bytes', models.IntegerField(verbose_name='Dateigroesse (Bytes)')),
                ('inhalt_roh', models.BinaryField(blank=True, null=True, verbose_name='Inhalt (unkryptiert)')),
                ('inhalt_verschluesselt', models.BinaryField(blank=True, null=True, verbose_name='Inhalt (AES-256-GCM)')),
                ('kommentar', models.CharField(blank=True, max_length=300, verbose_name='Kommentar')),
                ('verschluessel_nonce', models.CharField(blank=True, max_length=24, verbose_name='AES-GCM Nonce (Hex)')),
                ('version_nr', models.PositiveIntegerField(verbose_name='Versionsnummer')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versionen', to='dms.dokument', verbose_name='Dokument')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_versionen', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Dokument-Version',
                'verbose_name_plural': 'Dokument-Versionen',
                'ordering': ['-version_nr'],
                'unique_together': {('dokument', 'version_nr')},
            },
        ),
    ]
