# Generated by Django 6.0.3 on 2026-03-10 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_api_token'),
        ('workflow', '0007_add_claim_fields_to_workflowtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='workflow_vorschlag',
            field=models.ForeignKey(blank=True, help_text='Automatisch vorgeschlagener Workflow (gesetzt beim Paperless-Import).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vorgeschlagene_dokumente', to='workflow.workflowtemplate', verbose_name='Workflow-Vorschlag'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='workflow_vorschlag_erledigt',
            field=models.BooleanField(default=False, verbose_name='Workflow-Vorschlag erledigt'),
        ),
        migrations.CreateModel(
            name='PaperlessWorkflowRegel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(help_text="Interne Beschreibung der Regel, z.B. 'Eingangsrechnungen Elektro'.", max_length=200, verbose_name='Bezeichnung')),
                ('treffer_typ', models.CharField(choices=[('dokumenttyp', 'Paperless Dokumenttyp (Name)'), ('tag', 'Paperless Tag (Name)')], default='dokumenttyp', help_text='Ob der Name als Paperless-Dokumenttyp oder als Tag verglichen wird.', max_length=20, verbose_name='Treffer-Typ')),
                ('paperless_name', models.CharField(help_text="Name des Dokumenttyps oder Tags in Paperless-ngx (Gross/Kleinschreibung egal). Beispiel: 'Rechnung' oder 'elektro'.", max_length=200, verbose_name='Paperless-Name')),
                ('prioritaet', models.PositiveSmallIntegerField(default=100, verbose_name='Prioritaet (niedrig = zuerst geprueft)')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('workflow_template', models.ForeignKey(help_text='Dieses Template wird als Vorschlag gesetzt wenn die Regel greift.', on_delete=django.db.models.deletion.CASCADE, related_name='paperless_regeln', to='workflow.workflowtemplate', verbose_name='Workflow-Template')),
            ],
            options={
                'verbose_name': 'Paperless-Workflow-Regel',
                'verbose_name_plural': 'Paperless-Workflow-Regeln',
                'ordering': ['prioritaet', 'bezeichnung'],
            },
        ),
    ]
