# Generated by Django 6.0.3 on 2026-03-10 07:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_paperless_workflow_regel'),
        ('hr', '0009_personalstammdaten'),
        ('workflow', '0007_add_claim_fields_to_workflowtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Alten funktionalen GIN-Index aus Migration 0002 entfernen (war auf
        # to_tsvector(titel||beschreibung), wurde nie fuer die Suche genutzt).
        migrations.RunSQL(
            "DROP INDEX IF EXISTS dms_dokument_suchvektor_gin",
            reverse_sql="CREATE INDEX IF NOT EXISTS dms_dokument_suchvektor_gin "
                        "ON dms_dokument USING GIN "
                        "(to_tsvector('german', COALESCE(titel,'') || ' ' || COALESCE(beschreibung,'')))",
        ),
        migrations.AddField(
            model_name='dokument',
            name='ocr_text',
            field=models.TextField(blank=True, editable=False, verbose_name='OCR-Text'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='suchvektor',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True, verbose_name='Suchvektor'),
        ),
        migrations.AddIndex(
            model_name='dokument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['suchvektor'], name='dms_dokument_suchvektor_gin2'),
        ),
    ]
