# Generated by Django 6.0.3 on 2026-03-14 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0008_fts_suchvektor_tsvektor'),
        ('workflow', '0012_workflow_trigger_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dms_dokumente', to='workflow.workflowinstance', verbose_name='Workflow-Instanz'),
        ),
    ]
