# Generated by Django 6.0.3 on 2026-03-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0012_zugriffsprotokoll_loeschung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zugriffsprotokoll',
            name='aktion',
            field=models.CharField(choices=[('download', 'Download'), ('vorschau', 'Vorschau'), ('erstellt', 'Erstellt'), ('geaendert', 'Geaendert'), ('zugriff_beantragt', 'Zugriff beantragt'), ('zugriff_genehmigt', 'Zugriff genehmigt'), ('zugriff_abgelehnt', 'Zugriff abgelehnt'), ('zugriff_widerrufen', 'Zugriff widerrufen'), ('onlyoffice_bearbeitet', 'In OnlyOffice bearbeitet'), ('version_wiederhergestellt', 'Version wiederhergestellt'), ('api_upload', 'API-Upload (externes System)'), ('api_download', 'API-Download (externes System)'), ('loeschen', 'Loeschantrag gestellt'), ('geloescht', 'Dokument geloescht')], default='download', max_length=25, verbose_name='Aktion'),
        ),
        migrations.AlterField(
            model_name='zugriffsprotokoll',
            name='dokument_titel',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dokument-Titel (Sicherungskopie)'),
        ),
    ]
