# Generated by Django 6.0.2 on 2026-03-02 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0007_alter_hrmitarbeiter_personalnummer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbaustein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(choices=[('elektro', 'Elektro'), ('sanitaer_heizung', 'Sanitaer / Heizung'), ('schlosser', 'Schlosser'), ('schreiner', 'Schreiner'), ('maler', 'Maler')], max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('ist_aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Textbaustein',
                'verbose_name_plural': 'Textbausteine',
                'ordering': ['kategorie', 'reihenfolge', 'text'],
            },
        ),
        migrations.CreateModel(
            name='FacilityTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(choices=[('elektro', 'Elektro'), ('sanitaer_heizung', 'Sanitaer / Heizung'), ('schlosser', 'Schlosser'), ('schreiner', 'Schreiner'), ('maler', 'Maler')], max_length=30, unique=True)),
                ('eskalation_nach_tagen', models.PositiveIntegerField(default=3)),
                ('mitglieder', models.ManyToManyField(blank=True, related_name='facility_teams', to=settings.AUTH_USER_MODEL)),
                ('teamleiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geleitete_facility_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facility-Team',
                'verbose_name_plural': 'Facility-Teams',
                'ordering': ['kategorie'],
            },
        ),
        migrations.CreateModel(
            name='Stoermeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melder_telefon', models.CharField(max_length=50)),
                ('raumnummer', models.CharField(max_length=50)),
                ('raum_freitext', models.TextField(blank=True)),
                ('raumbuch_id', models.PositiveIntegerField(blank=True, null=True)),
                ('kategorie', models.CharField(choices=[('elektro', 'Elektro'), ('sanitaer_heizung', 'Sanitaer / Heizung'), ('schlosser', 'Schlosser'), ('schreiner', 'Schreiner'), ('maler', 'Maler')], max_length=30)),
                ('beschreibung', models.TextField(blank=True)),
                ('prioritaet', models.CharField(choices=[('normal', 'Normal'), ('dringend', 'Dringend'), ('sofort', 'Sofort / Notfall')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt'), ('unloesbar', 'Unloesbar / Eskaliert')], default='offen', max_length=30)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('claimed_am', models.DateTimeField(blank=True, null=True)),
                ('bearbeitet_am', models.DateTimeField(blank=True, null=True)),
                ('erledigungs_kommentar', models.TextField(blank=True)),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bearbeitete_stoermeldungen', to=settings.AUTH_USER_MODEL)),
                ('claimed_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geclaimte_stoermeldungen', to=settings.AUTH_USER_MODEL)),
                ('melder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stoermeldungen', to='hr.hrmitarbeiter')),
                ('textbaustein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.textbaustein')),
            ],
            options={
                'verbose_name': 'Stoermeldung',
                'verbose_name_plural': 'Stoermeldungen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
