# Generated by Django 6.0.2 on 2026-03-04 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stoermeldung',
            name='ist_wartung',
            field=models.BooleanField(default=False, help_text='Automatisch ausgeloest durch einen Wartungsplan.', verbose_name='Wartungsaufgabe'),
        ),
        migrations.CreateModel(
            name='Wartungsplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('kategorie', models.CharField(choices=[('elektro', 'Elektro'), ('sanitaer_heizung', 'Sanitaer / Heizung'), ('schlosser', 'Schlosser'), ('schreiner', 'Schreiner'), ('maler', 'Maler')], max_length=30, verbose_name='Kategorie')),
                ('raumnummer', models.CharField(max_length=50, verbose_name='Raumnummer / Ort')),
                ('raum_freitext', models.TextField(blank=True, verbose_name='Ort-Zusatz')),
                ('prioritaet', models.CharField(choices=[('normal', 'Normal'), ('dringend', 'Dringend'), ('sofort', 'Sofort / Notfall')], default='normal', max_length=20, verbose_name='Prioritaet')),
                ('intervall_wert', models.PositiveIntegerField(help_text='Zahl fuer das Wartungsintervall (z.B. 30)', verbose_name='Intervall')),
                ('intervall_einheit', models.CharField(choices=[('tage', 'Tage'), ('wochen', 'Wochen'), ('monate', 'Monate')], default='tage', max_length=10, verbose_name='Einheit')),
                ('letzte_ausfuehrung', models.DateField(blank=True, help_text='Wird automatisch gesetzt wenn eine Wartungsaufgabe erledigt wird.', null=True, verbose_name='Letzte Ausfuehrung')),
                ('naechste_faelligkeit', models.DateField(help_text='Wird automatisch berechnet.', verbose_name='Naechste Faelligkeit')),
                ('ist_aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_wartungsplaene', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wartungsplan',
                'verbose_name_plural': 'Wartungsplaene',
                'ordering': ['naechste_faelligkeit', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stoermeldung',
            name='wartungsplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausgeloeste_meldungen', to='facility.wartungsplan'),
        ),
    ]
