# Generated by Django 6.0.2 on 2026-03-04 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_stoermeldung_ist_wartung_wartungsplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stoermeldung',
            name='eskalation_antwort',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stoermeldung',
            name='eskalation_kommentar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stoermeldung',
            name='eskalation_typ',
            field=models.CharField(blank=True, choices=[('bestellware', 'Bestellware'), ('eskalation', 'Eskalation')], max_length=20),
        ),
        migrations.AddField(
            model_name='stoermeldung',
            name='eskaliert_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stoermeldung',
            name='eskaliert_an',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eskalierte_stoermeldungen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stoermeldung',
            name='status',
            field=models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('weitergeleitet', 'Weitergeleitet an AL'), ('erledigt', 'Erledigt'), ('unloesbar', 'Unloesbar / Eskaliert')], default='offen', max_length=30),
        ),
    ]
