# Generated by Django 6.0.2 on 2026-03-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_stoermeldung_weiterleitung'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityEinstellungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_schwelle', models.PositiveIntegerField(default=3, help_text='Ab dieser Wiederholungsanzahl am gleichen Ort und gleicher Kategorie wird im Monatsbericht eine Tendenz-Warnung ausgegeben.', verbose_name='Trend-Schwelle (Anzahl Meldungen)')),
                ('trend_tage', models.PositiveIntegerField(default=90, help_text='Zeitraum in Tagen, ueber den Meldungen auf Tendenzen geprueft werden. Empfehlung: 30 (Monat), 90 (Quartal) oder 180 (Halbjahr).', verbose_name='Beobachtungszeitraum (Tage)')),
            ],
            options={
                'verbose_name': 'Facility-Einstellungen',
                'verbose_name_plural': 'Facility-Einstellungen',
            },
        ),
    ]
