# Generated by Django 6.0.2 on 2026-03-04 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_facility_einstellungen'),
        ('raumbuch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoermeldung',
            name='raumbuch_id',
        ),
        migrations.AddField(
            model_name='stoermeldung',
            name='raum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stoermeldungen', to='raumbuch.raum', verbose_name='Raum (Raumbuch)'),
        ),
    ]
