# Generated by Django 6.0.2 on 2026-03-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_remove_stoermeldung_raumbuch_id_stoermeldung_raum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoermeldung',
            name='kategorie',
            field=models.CharField(choices=[('elektro', 'Elektro'), ('sanitaer_heizung', 'Sanitaer / Heizung'), ('schlosser', 'Schlosser'), ('schreiner', 'Schreiner'), ('maler', 'Maler')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stoermeldung',
            name='status',
            field=models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('weitergeleitet', 'Weitergeleitet an AL'), ('erledigt', 'Erledigt'), ('unloesbar', 'Unloesbar / Eskaliert')], db_index=True, default='offen', max_length=30),
        ),
    ]
