# Generated by Django 6.0.3 on 2026-03-08 20:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0009_personalstammdaten'),
        ('raumbuch', '0003_jitsi_link_raumbuchung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('gutschrift_stunden', models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Max. 1 Stunde pro Woche anrechenbar.', max_digits=3, verbose_name='Gutschrift-Stunden pro Einheit')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('ort_beschreibung', models.CharField(blank=True, help_text='z.B. Turnhalle Hauptgebaeude, Sportplatz Nord', max_length=200, verbose_name='Ort')),
                ('sportart', models.CharField(choices=[('fussball', 'Fussball'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('laufen', 'Laufen / Joggen'), ('radfahren', 'Radfahren'), ('schwimmen', 'Schwimmen'), ('yoga', 'Yoga / Meditation'), ('fitness', 'Fitness / Krafttraining'), ('tischtennis', 'Tischtennis'), ('sonstiges', 'Sonstiges')], max_length=30, verbose_name='Sportart')),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('pausiert', 'Pausiert'), ('aufgeloest', 'Aufgeloest')], default='aktiv', max_length=20, verbose_name='Status')),
                ('uhrzeit_bis', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit bis')),
                ('uhrzeit_von', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit von')),
                ('wochentag', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], verbose_name='Wochentag')),
                ('standort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sportgruppen', to='raumbuch.standort', verbose_name='Standort')),
                ('verantwortlicher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geleitete_sportgruppen', to='hr.hrmitarbeiter', verbose_name='Verantwortlicher')),
            ],
            options={
                'verbose_name': 'Sportgruppe',
                'verbose_name_plural': 'Sportgruppen',
                'ordering': ['sportart', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sporteinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('notiz', models.TextField(blank=True, verbose_name='Notiz')),
                ('status', models.CharField(choices=[('geplant', 'Geplant'), ('stattgefunden', 'Stattgefunden'), ('ausgefallen', 'Ausgefallen')], default='geplant', max_length=20, verbose_name='Status')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_sporteinheiten', to='hr.hrmitarbeiter', verbose_name='Erstellt von')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einheiten', to='betriebssport.sportgruppe', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Sporteinheit',
                'verbose_name_plural': 'Sporteinheiten',
                'ordering': ['datum'],
                'unique_together': {('gruppe', 'datum')},
            },
        ),
        migrations.CreateModel(
            name='SportgruppeMitglied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beigetreten_am', models.DateTimeField(auto_now_add=True)),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitgliedschaften', to='betriebssport.sportgruppe')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_mitgliedschaften', to='hr.hrmitarbeiter')),
            ],
            options={
                'verbose_name': 'Sportgruppen-Mitglied',
                'verbose_name_plural': 'Sportgruppen-Mitglieder',
                'unique_together': {('gruppe', 'mitarbeiter')},
            },
        ),
        migrations.AddField(
            model_name='sportgruppe',
            name='mitglieder',
            field=models.ManyToManyField(blank=True, related_name='sportgruppen', through='betriebssport.SportgruppeMitglied', to='hr.hrmitarbeiter', verbose_name='Mitglieder'),
        ),
        migrations.CreateModel(
            name='BetriebssportGutschrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('eingereicht_am', models.DateTimeField(blank=True, null=True, verbose_name='Eingereicht am')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('monat', models.DateField(help_text='Erster Tag des abzurechnenden Monats (z.B. 2026-03-01).', verbose_name='Monat')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('eingereicht', 'Eingereicht'), ('abgeschlossen', 'Abgeschlossen'), ('abgelehnt', 'Abgelehnt')], default='entwurf', max_length=20, verbose_name='Status')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_bssport_gutschriften', to='hr.hrmitarbeiter', verbose_name='Erstellt von')),
                ('einheiten', models.ManyToManyField(blank=True, related_name='gutschriften', to='betriebssport.sporteinheit', verbose_name='Einheiten')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gutschriften', to='betriebssport.sportgruppe', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Betriebssport-Gutschrift',
                'verbose_name_plural': 'Betriebssport-Gutschriften',
                'ordering': ['-monat'],
                'unique_together': {('gruppe', 'monat')},
            },
        ),
        migrations.CreateModel(
            name='Sportteilnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markiert_am', models.DateTimeField(auto_now_add=True)),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to='betriebssport.sporteinheit', verbose_name='Einheit')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_teilnahmen', to='hr.hrmitarbeiter', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Sportteilnahme',
                'verbose_name_plural': 'Sportteilnahmen',
                'unique_together': {('einheit', 'mitarbeiter')},
            },
        ),
    ]
