# Generated by Django 6.0.3 on 2026-03-16 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
                ('ping_url', models.URLField(blank=True, help_text='Wird alle 5 Minuten per HTTP-GET geprueft. Leer lassen fuer manuellen Status.', verbose_name='URL fuer automatischen Ping')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=10)),
                ('aktiv', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ok', 'Betrieb normal'), ('warnung', 'Warnung'), ('gestoert', 'Gestoert'), ('wartung', 'Wartung')], default='ok', max_length=20)),
            ],
            options={
                'verbose_name': 'IT-System',
                'verbose_name_plural': 'IT-Systeme',
                'ordering': ['reihenfolge', 'bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='ITStatusMeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'Betrieb normal'), ('warnung', 'Warnung'), ('gestoert', 'Gestoert'), ('wartung', 'Wartung')], max_length=20)),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geloest_am', models.DateTimeField(blank=True, null=True)),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_meldungen', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meldungen', to='it_status.itsystem')),
            ],
            options={
                'verbose_name': 'Statusmeldung',
                'verbose_name_plural': 'Statusmeldungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='ITWartung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('ende', models.DateTimeField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_wartungen', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wartungen', to='it_status.itsystem')),
            ],
            options={
                'verbose_name': 'Wartungsfenster',
                'verbose_name_plural': 'Wartungsfenster',
                'ordering': ['start'],
            },
        ),
    ]
