# Generated by Django 6.0.3 on 2026-03-16 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_status', '0001_initial'),
        ('workflow', '0015_alter_workflowstep_aktion_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='itstatusmeldung',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_meldungen', to='workflow.workflowinstance', verbose_name='Workflow-Instanz'),
        ),
    ]
