# Generated by Django 6.0.2 on 2026-02-18 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arbeitszeit', '0023_ersteinrichtung_antragsart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AenderungZeiterfassung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('bearbeitet_am', models.DateTimeField(blank=True, null=True)),
                ('bemerkung_bearbeiter', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt')], default='beantragt', max_length=20)),
                ('art', models.CharField(choices=[('beruflich_unterwegs', 'Beruflich unterwegs'), ('b_taste', 'B-Taste'), ('k_taste', 'K-Taste')], max_length=30)),
                ('gehen_datum', models.DateField(blank=True, null=True)),
                ('gehen_terminal', models.CharField(blank=True, choices=[('bedient', 'Bedient'), ('nicht_bedient', 'Nicht bedient')], max_length=20)),
                ('kommen_datum', models.DateField(blank=True, null=True)),
                ('kommen_terminal', models.CharField(blank=True, choices=[('bedient', 'Bedient'), ('nicht_bedient', 'Nicht bedient')], max_length=20)),
                ('ktaste_datum', models.DateField(blank=True, null=True)),
                ('ktaste_terminal', models.CharField(blank=True, choices=[('bedient', 'Bedient'), ('nicht_bedient', 'Nicht bedient')], max_length=20)),
                ('antragsteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_antraege', to='arbeitszeit.mitarbeiter')),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_bearbeitet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aenderung Zeiterfassung',
                'verbose_name_plural': 'Aenderungen Zeiterfassung',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
