# Generated by Django 6.0.2 on 2026-02-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aenderungzeiterfassung',
            name='ktaste_terminal',
            field=models.CharField(blank=True, choices=[('nicht_bedient', 'Nicht bedient'), ('versehentlich_bedient', 'Versehentlich bedient')], max_length=22),
        ),
    ]
