# Generated by Django 6.0.2 on 2026-02-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0002_alter_aenderungzeiterfassung_ktaste_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='gehen_zeit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='kommen_zeit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='pause_gehen_zeit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='pause_kommen_zeit',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='tages_datum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
