# Generated by Django 6.0.2 on 2026-02-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0003_aenderungzeiterfassung_gehen_zeit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='samstag_art',
            field=models.CharField(blank=True, choices=[('im_betrieb', 'Im Betrieb (automatische Erfassung 06:00 - 18:00)'), ('ausserhalb', 'Außerhalb des Betriebes'), ('dauerfreigabe', 'Ich habe eine Dauerfreigabe für Samstagsarbeit')], max_length=20),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='samstag_beginn',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='samstag_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='samstag_ende',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='samstag_freigabe_ab',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='samstag_freigabe_bis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='samstag_vereinbarungsnummer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
