# Generated by Django 6.0.2 on 2026-02-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0004_aenderungzeiterfassung_samstag_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aenderungzeiterfassung',
            name='art',
            field=models.CharField(blank=True, choices=[('beruflich_unterwegs', 'Beruflich unterwegs'), ('b_taste', 'B-Taste'), ('k_taste', 'K-Taste')], max_length=30),
        ),
    ]
