# Generated by Django 6.0.2 on 2026-02-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0005_alter_aenderungzeiterfassung_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='tausch_daten',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='zeiten_daten',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
