# Generated by Django 6.0.2 on 2026-02-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0007_zag_antrag'),
    ]

    operations = [
        migrations.AddField(
            model_name='zagantrag',
            name='vertretung_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='zagantrag',
            name='vertretung_telefon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
