# Generated by Django 6.0.2 on 2026-02-19 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0023_ersteinrichtung_antragsart'),
        ('formulare', '0008_zag_vertretungsfelder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZAGStorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('bearbeitet_am', models.DateTimeField(blank=True, null=True)),
                ('bemerkung_bearbeiter', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt')], default='beantragt', max_length=20)),
                ('storno_daten', models.JSONField(blank=True, null=True)),
                ('antragsteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_antraege', to='arbeitszeit.mitarbeiter')),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_bearbeitet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Z-AG Storno',
                'verbose_name_plural': 'Z-AG Stornierungen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
