# Generated by Django 6.0.2 on 2026-02-20 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0009_zag_storno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='claimed_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Claimed am'),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='claimed_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_claimed', to=settings.AUTH_USER_MODEL, verbose_name='Claimed von'),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='erledigt_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am'),
        ),
        migrations.AddField(
            model_name='aenderungzeiterfassung',
            name='prioritaet',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Hoch'), (2, 'Dringend')], default=0, verbose_name='Prioritaet'),
        ),
        migrations.AddField(
            model_name='zagantrag',
            name='claimed_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Claimed am'),
        ),
        migrations.AddField(
            model_name='zagantrag',
            name='claimed_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_claimed', to=settings.AUTH_USER_MODEL, verbose_name='Claimed von'),
        ),
        migrations.AddField(
            model_name='zagantrag',
            name='erledigt_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am'),
        ),
        migrations.AddField(
            model_name='zagantrag',
            name='prioritaet',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Hoch'), (2, 'Dringend')], default=0, verbose_name='Prioritaet'),
        ),
        migrations.AddField(
            model_name='zagstorno',
            name='claimed_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Claimed am'),
        ),
        migrations.AddField(
            model_name='zagstorno',
            name='claimed_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_claimed', to=settings.AUTH_USER_MODEL, verbose_name='Claimed von'),
        ),
        migrations.AddField(
            model_name='zagstorno',
            name='erledigt_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am'),
        ),
        migrations.AddField(
            model_name='zagstorno',
            name='prioritaet',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Hoch'), (2, 'Dringend')], default=0, verbose_name='Prioritaet'),
        ),
        migrations.AlterField(
            model_name='aenderungzeiterfassung',
            name='status',
            field=models.CharField(choices=[('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('eskaliert', 'Eskaliert'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='beantragt', max_length=20),
        ),
        migrations.AlterField(
            model_name='zagantrag',
            name='status',
            field=models.CharField(choices=[('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('eskaliert', 'Eskaliert'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='beantragt', max_length=20),
        ),
        migrations.AlterField(
            model_name='zagstorno',
            name='status',
            field=models.CharField(choices=[('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('eskaliert', 'Eskaliert'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='beantragt', max_length=20),
        ),
        migrations.CreateModel(
            name='TeamQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(blank=True, help_text='Beschreibung des Teams und seiner Zustaendigkeiten.')),
                ('kuerzel', models.CharField(help_text="Eindeutiges Kuerzel (z.B. 'zeit', 'hr').", max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Team-Name')),
                ('mitglieder', models.ManyToManyField(blank=True, related_name='team_queues', to=settings.AUTH_USER_MODEL, verbose_name='Mitglieder')),
            ],
            options={
                'verbose_name': 'Team-Queue',
                'verbose_name_plural': 'Team-Queues',
                'ordering': ['name'],
            },
        ),
    ]
