# Generated by Django 6.0.2 on 2026-02-23 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0026_vorgesetzter_feld'),
        ('formulare', '0010_aenderungzeiterfassung_claimed_am_and_more'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dienstreiseantrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('bearbeitet_am', models.DateTimeField(blank=True, null=True)),
                ('bemerkung_bearbeiter', models.TextField(blank=True)),
                ('claimed_am', models.DateTimeField(blank=True, null=True, verbose_name='Claimed am')),
                ('erledigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('prioritaet', models.IntegerField(choices=[(0, 'Normal'), (1, 'Hoch'), (2, 'Dringend')], default=0, verbose_name='Prioritaet')),
                ('status', models.CharField(choices=[('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('eskaliert', 'Eskaliert'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='beantragt', max_length=20)),
                ('von_datum', models.DateField(verbose_name='Reisebeginn')),
                ('bis_datum', models.DateField(verbose_name='Reiseende')),
                ('ziel', models.CharField(help_text='Stadt, Land oder Veranstaltungsort', max_length=200, verbose_name='Reiseziel')),
                ('zweck', models.TextField(help_text='Grund und Ziel der Reise (z.B. Kundentermin, Schulung, Messe)', verbose_name='Zweck der Dienstreise')),
                ('geschaetzte_kosten', models.DecimalField(decimal_places=2, default=0, help_text='Geschaetzte Gesamtkosten inkl. Fahrt, Unterkunft, Verpflegung', max_digits=10, verbose_name='Geschaetzte Kosten (EUR)')),
                ('einladungscode', models.CharField(blank=True, help_text='Code fuer Mitarbeiter um Reisezeit-Antrag zu stellen', max_length=20, unique=True, verbose_name='Einladungscode')),
                ('antragsteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_antraege', to='arbeitszeit.mitarbeiter')),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_bearbeitet', to=settings.AUTH_USER_MODEL)),
                ('claimed_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_claimed', to=settings.AUTH_USER_MODEL, verbose_name='Claimed von')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dienstreiseantraege', to='workflow.workflowinstance', verbose_name='Workflow-Instanz')),
            ],
            options={
                'verbose_name': 'Dienstreiseantrag',
                'verbose_name_plural': 'Dienstreiseantraege',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
