# Generated by Django 6.0.2 on 2026-02-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0011_dienstreiseantrag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dienstreiseantrag',
            name='einladungscode',
            field=models.CharField(blank=True, help_text='Code fuer Mitarbeiter um Reisezeit-Antrag zu stellen', max_length=20, null=True, unique=True, verbose_name='Einladungscode'),
        ),
    ]
