# Generated by Django 6.0.2 on 2026-02-25 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0026_vorgesetzter_feld'),
        ('formulare', '0012_alter_dienstreiseantrag_einladungscode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zeitgutschrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('bearbeitet_am', models.DateTimeField(blank=True, null=True)),
                ('bemerkung_bearbeiter', models.TextField(blank=True)),
                ('claimed_am', models.DateTimeField(blank=True, null=True, verbose_name='Claimed am')),
                ('erledigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('prioritaet', models.IntegerField(choices=[(0, 'Normal'), (1, 'Hoch'), (2, 'Dringend')], default=0, verbose_name='Prioritaet')),
                ('status', models.CharField(choices=[('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('eskaliert', 'Eskaliert'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='beantragt', max_length=20)),
                ('art', models.CharField(choices=[('haertefall', 'Haertefallregelung'), ('ehrenamt', 'Wahrnehmung von Ehrenamtern'), ('fortbildung', 'Ganztaegige Fortbildung bei individueller Arbeitszeit')], max_length=20)),
                ('zeilen_daten', models.JSONField(blank=True, null=True)),
                ('fortbildung_aktiv', models.BooleanField(default=False)),
                ('fortbildung_typ', models.CharField(blank=True, choices=[('typ_a', 'Typ A'), ('typ_b', 'Typ B')], max_length=10)),
                ('fortbildung_wochenstunden_regulaer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fortbildung_von_datum', models.DateField(blank=True, null=True)),
                ('fortbildung_bis_datum', models.DateField(blank=True, null=True)),
                ('fortbildung_massnahme_nr', models.CharField(blank=True, max_length=100)),
                ('fortbildung_berechnung', models.JSONField(blank=True, null=True)),
                ('antragsteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_antraege', to='arbeitszeit.mitarbeiter')),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_bearbeitet', to=settings.AUTH_USER_MODEL)),
                ('claimed_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_claimed', to=settings.AUTH_USER_MODEL, verbose_name='Claimed von')),
            ],
            options={
                'verbose_name': 'Zeitgutschrift',
                'verbose_name_plural': 'Zeitgutschriften',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='ZeitgutschriftBeleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datei', models.FileField(upload_to='zeitgutschriften/belege/%Y/%m/')),
                ('dateiname_original', models.CharField(max_length=255)),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('zeitgutschrift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belege', to='formulare.zeitgutschrift')),
            ],
            options={
                'verbose_name': 'Zeitgutschrift-Beleg',
                'verbose_name_plural': 'Zeitgutschrift-Belege',
                'ordering': ['hochgeladen_am'],
            },
        ),
    ]
