# Generated by Django 6.0.2 on 2026-02-25 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0013_zeitgutschrift_zeitgutschriftbeleg'),
        ('workflow', '0004_add_workflow_instance_to_zeitgutschrift'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeitgutschrift',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zeitgutschriften', to='workflow.workflowinstance', verbose_name='Workflow-Instanz'),
        ),
    ]
