# Generated by Django 6.0.2 on 2026-03-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0015_add_workflow_instance_to_aenderung'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeitgutschrift',
            name='erkrankung_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeitgutschrift',
            name='erkrankung_gutschrift_stunden',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='zeitgutschrift',
            name='erkrankung_tagesstunden',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='zeitgutschrift',
            name='erkrankung_typ',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='zeitgutschrift',
            name='erkrankung_wochenstunden',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='zeitgutschrift',
            name='art',
            field=models.CharField(choices=[('haertefall', 'Haertefallregelung'), ('ehrenamt', 'Wahrnehmung von Ehrenamtern'), ('fortbildung', 'Ganztaegige Fortbildung bei individueller Arbeitszeit'), ('erkrankung_angehoerige', 'Erkrankung eines im Haushalt lebenden Angehoerigen')], max_length=30),
        ),
    ]
