# Generated by Django 6.0.2 on 2026-03-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0016_erkrankung_angehoerige'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeitgutschrift',
            name='art',
            field=models.CharField(choices=[('haertefall', 'Haertefallregelung'), ('ehrenamt', 'Wahrnehmung von Ehrenamtern'), ('fortbildung', 'Ganztaegige Fortbildung bei individueller Arbeitszeit'), ('erkrankung_angehoerige', 'Erkrankung eines im Haushalt lebenden Angehoerigen'), ('erkrankung_kind', 'Erkrankung eines Kindes unter 12 Jahren oder eines behinderten und auf Hilfe angewiesenen Kindes')], max_length=30),
        ),
    ]
