# Generated by Django 6.0.2 on 2026-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0018_erkrankung_betreuung'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeitgutschrift',
            name='mehrarbeit_begruendung',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zeitgutschrift',
            name='mehrarbeit_buchungsjahr',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeitgutschrift',
            name='mehrarbeit_buchungsmonat',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeitgutschrift',
            name='mehrarbeit_minuten',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeitgutschrift',
            name='mehrarbeit_stunden',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zeitgutschrift',
            name='art',
            field=models.CharField(choices=[('haertefall', 'Haertefallregelung'), ('ehrenamt', 'Wahrnehmung von Ehrenamtern'), ('fortbildung', 'Ganztaegige Fortbildung bei individueller Arbeitszeit'), ('erkrankung_angehoerige', 'Erkrankung eines im Haushalt lebenden Angehoerigen'), ('erkrankung_kind', 'Erkrankung eines Kindes unter 12 Jahren oder eines behinderten und auf Hilfe angewiesenen Kindes'), ('erkrankung_betreuung', 'Erkrankung einer Betreuungsperson fuer das unter acht Jahre alte oder dauernd pflegebeduerfte Kind'), ('mehrarbeit', 'Abbuchung von Mehrarbeit vom Zeitkonto')], max_length=30),
        ),
    ]
