# Generated by Django 6.0.2 on 2026-03-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0021_ueberstunden_buchung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeitgutschrift',
            name='art',
            field=models.CharField(choices=[('haertefall', 'Haertefallregelung'), ('ehrenamt', 'Wahrnehmung von Ehrenamtern'), ('fortbildung', 'Ganztaegige Fortbildung bei individueller Arbeitszeit'), ('erkrankung_angehoerige', 'Erkrankung eines im Haushalt lebenden Angehoerigen'), ('erkrankung_kind', 'Erkrankung eines Kindes unter 12 Jahren oder eines behinderten und auf Hilfe angewiesenen Kindes'), ('erkrankung_betreuung', 'Erkrankung einer Betreuungsperson fuer das unter acht Jahre alte oder dauernd pflegebeduerfte Kind'), ('mehrarbeit', 'Abbuchung von Mehrarbeit vom Zeitkonto'), ('mehrarbeit_buchung', 'Buchung von Mehrarbeitszeit auf das Zeitkonto zum Ausgleich eines Minus / fuer stundenweise erfolgten Freizeitausgleich'), ('ueberstunden_buchung', 'Buchung von Zeitguthaben aus angeordneten Ueberstunden auf das Zeitkonto'), ('rufbereitschaft_buchung', 'Buchung von Zeitguthaben aus angeordneter Rufbereitschaft auf das Zeitkonto')], max_length=30),
        ),
    ]
