# Generated by Django 6.0.2 on 2026-03-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0023_sonstige_anliegen'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeitgutschrift',
            name='reisezeit_dienstreise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reisezeit_gutschriften', to='formulare.dienstreiseantrag', verbose_name='Zugehoerige Dienstreise'),
        ),
        migrations.AlterField(
            model_name='zeitgutschrift',
            name='art',
            field=models.CharField(choices=[('haertefall', 'Haertefallregelung'), ('ehrenamt', 'Wahrnehmung von Ehrenamtern'), ('fortbildung', 'Ganztaegige Fortbildung bei individueller Arbeitszeit'), ('erkrankung_angehoerige', 'Erkrankung eines im Haushalt lebenden Angehoerigen'), ('erkrankung_kind', 'Erkrankung eines Kindes unter 12 Jahren oder eines behinderten und auf Hilfe angewiesenen Kindes'), ('erkrankung_betreuung', 'Erkrankung einer Betreuungsperson fuer das unter acht Jahre alte oder dauernd pflegebeduerfte Kind'), ('mehrarbeit', 'Abbuchung von Mehrarbeit vom Zeitkonto'), ('mehrarbeit_buchung', 'Buchung von Mehrarbeitszeit auf das Zeitkonto zum Ausgleich eines Minus / fuer stundenweise erfolgten Freizeitausgleich'), ('ueberstunden_buchung', 'Buchung von Zeitguthaben aus angeordneten Ueberstunden auf das Zeitkonto'), ('rufbereitschaft_buchung', 'Buchung von Zeitguthaben aus angeordneter Rufbereitschaft auf das Zeitkonto'), ('sonstige', 'Sonstige Anliegen'), ('reisezeit_tagebuch', 'Reisezeit-Tagebuch (Dienstreise)')], max_length=30),
        ),
        migrations.CreateModel(
            name='ReisezeitTagebuchEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemerkung', models.TextField(blank=True)),
                ('bis_zeit', models.TimeField()),
                ('datum', models.DateField()),
                ('fall', models.PositiveSmallIntegerField(choices=[(1, 'Fall 1 – Normalarbeitszeit vom Standort (keine Gutschrift)'), (2, 'Fall 2 – Gesamtzeit waehrend Arbeitstag (Differenz zur Regelarbeitszeit)'), (3, 'Fall 3 – Reisezeit ausserhalb Arbeitszeit (1/3 als Gutschrift)')])),
                ('von_zeit', models.TimeField()),
                ('dienstreise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagebuch_eintraege', to='formulare.dienstreiseantrag')),
            ],
            options={
                'verbose_name': 'Reisezeit-Tagebucheintrag',
                'verbose_name_plural': 'Reisezeit-Tagebucheintraege',
                'ordering': ['datum', 'von_zeit'],
            },
        ),
    ]
