# Generated by Django 6.0.2 on 2026-03-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0024_reisezeit_tagebuch'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamqueue',
            name='antragstypen',
            field=models.JSONField(blank=True, default=list, help_text="Liste der Antragstypen die dieses Team bearbeitet (z.B. ['zag', 'aenderung'])."),
        ),
    ]
