# Generated by Django 6.0.2 on 2026-03-07 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RootCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zertifikat_pem', models.TextField(verbose_name='Root-Zertifikat (PEM)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('gueltig_bis', models.DateField()),
                ('organisation', models.CharField(default='Intern', max_length=200)),
                ('common_name', models.CharField(default='Interne Root CA', max_length=200)),
            ],
            options={
                'verbose_name': 'Root-CA',
                'verbose_name_plural': 'Root-CA',
            },
        ),
        migrations.CreateModel(
            name='MitarbeiterZertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zertifikat_pem', models.TextField(verbose_name='Zertifikat (PEM)')),
                ('privater_schluessel_pem', models.TextField(verbose_name='Privater Schluessel (PEM, verschluesselt)')),
                ('seriennummer', models.CharField(max_length=100, unique=True)),
                ('ausgestellt_am', models.DateTimeField(auto_now_add=True)),
                ('gueltig_von', models.DateField()),
                ('gueltig_bis', models.DateField()),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('gesperrt', 'Gesperrt'), ('abgelaufen', 'Abgelaufen')], default='aktiv', max_length=20)),
                ('fingerprint_sha256', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signatur_zertifikat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mitarbeiter-Zertifikat',
                'verbose_name_plural': 'Mitarbeiter-Zertifikate',
                'ordering': ['-ausgestellt_am'],
            },
        ),
        migrations.CreateModel(
            name='SignaturJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('backend', models.CharField(choices=[('intern', 'Intern (pyhanko)'), ('sign_me', 'sign-me (Bundesdruckerei)'), ('gateway', 'Gateway (intern → sign-me)')], default='intern', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('dokument_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fehler_meldung', models.TextField(blank=True)),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatur_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signatur-Job',
                'verbose_name_plural': 'Signatur-Jobs',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='SignaturProtokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signiert_am', models.DateTimeField(auto_now_add=True)),
                ('hash_sha256', models.CharField(max_length=64, verbose_name='SHA-256 Dokumenten-Hash')),
                ('signatur_typ', models.CharField(choices=[('FES', 'Fortgeschrittene Signatur'), ('QES', 'Qualifizierte Signatur')], default='FES', max_length=20)),
                ('signiertes_pdf', models.BinaryField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protokoll', to='signatur.signaturjob')),
                ('unterzeichner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signaturen', to=settings.AUTH_USER_MODEL)),
                ('zertifikat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signatur.mitarbeiterzertifikat')),
            ],
            options={
                'verbose_name': 'Signatur-Protokoll',
                'verbose_name_plural': 'Signatur-Protokolle',
                'ordering': ['-signiert_am'],
            },
        ),
    ]
