# Generated by Django 6.0.3 on 2026-03-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiterzertifikat',
            name='privater_schluessel_verschluesselt',
            field=models.BinaryField(blank=True, null=True, verbose_name='Privater Schluessel (AES-256-GCM verschluesselt)'),
        ),
        migrations.AddField(
            model_name='mitarbeiterzertifikat',
            name='schluessel_nonce',
            field=models.CharField(blank=True, max_length=24, verbose_name='Schluessel-Nonce (AES-GCM, hex)'),
        ),
        migrations.AddField(
            model_name='mitarbeiterzertifikat',
            name='schluessel_salt',
            field=models.CharField(blank=True, max_length=64, verbose_name='Schluessel-Salt (PBKDF2, hex)'),
        ),
        migrations.AlterField(
            model_name='mitarbeiterzertifikat',
            name='privater_schluessel_pem',
            field=models.TextField(blank=True, verbose_name='Privater Schluessel (PEM, Plaintext – wird migriert)'),
        ),
    ]
