from django.urls import path

from formulare import views
from formulare import views_team_queue

app_name = "formulare"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path(
        "meine-antraege/",
        views.meine_antraege,
        name="meine_antraege",
    ),
    path(
        "aenderung-zeiterfassung/",
        views.aenderung_zeiterfassung,
        name="aenderung_zeiterfassung",
    ),
    path(
        "aenderung-zeiterfassung/<int:pk>/erfolg/",
        views.aenderung_erfolg,
        name="aenderung_erfolg",
    ),
    path(
        "aenderung-zeiterfassung/<int:pk>/pdf/",
        views.aenderung_pdf,
        name="aenderung_pdf",
    ),
    path(
        "aenderung-zeiterfassung/felder/",
        views.aenderung_felder,
        name="aenderung_felder",
    ),
    path(
        "aenderung-zeiterfassung/neue-zeitzeile/",
        views.neue_zeitzeile,
        name="neue_zeitzeile",
    ),
    path(
        "aenderung-zeiterfassung/samstag-felder/",
        views.samstag_felder,
        name="samstag_felder",
    ),
    path(
        "aenderung-zeiterfassung/soll-fuer-datum/",
        views.soll_fuer_datum,
        name="soll_fuer_datum",
    ),
    path(
        "aenderung-zeiterfassung/neue-tauschzeile/",
        views.neue_tauschzeile,
        name="neue_tauschzeile",
    ),
    path(
        "aenderung-zeiterfassung/tausch-validierung/",
        views.tausch_validierung,
        name="tausch_validierung",
    ),
    path(
        "zag-antrag/",
        views.zag_antrag,
        name="zag_antrag",
    ),
    path(
        "zag-antrag/<int:pk>/erfolg/",
        views.zag_erfolg,
        name="zag_erfolg",
    ),
    path(
        "zag-antrag/<int:pk>/pdf/",
        views.zag_pdf,
        name="zag_pdf",
    ),
    path(
        "zag-antrag/neue-zeile/",
        views.neue_zag_zeile,
        name="neue_zag_zeile",
    ),
    path(
        "zag-antrag/tage-zaehlen/",
        views.zag_tage_zaehlen,
        name="zag_tage_zaehlen",
    ),
    path(
        "zag-storno/",
        views.zag_storno,
        name="zag_storno",
    ),
    path(
        "zag-storno/<int:pk>/erfolg/",
        views.zag_storno_erfolg,
        name="zag_storno_erfolg",
    ),
    path(
        "zag-storno/<int:pk>/pdf/",
        views.zag_storno_pdf,
        name="zag_storno_pdf",
    ),
    path(
        "zag-storno/neue-zeile/",
        views.neue_zag_storno_zeile,
        name="neue_zag_storno_zeile",
    ),
    path(
        "zag-storno/tage-zaehlen/",
        views.zag_storno_tage_zaehlen,
        name="zag_storno_tage_zaehlen",
    ),
    # Zeitgutschrift
    path(
        "zeitgutschrift/",
        views.zeitgutschrift_antrag,
        name="zeitgutschrift_antrag",
    ),
    path(
        "zeitgutschrift/<int:pk>/",
        views.zeitgutschrift_detail,
        name="zeitgutschrift_detail",
    ),
    path(
        "zeitgutschrift/<int:pk>/erfolg/",
        views.zeitgutschrift_erfolg,
        name="zeitgutschrift_erfolg",
    ),
    path(
        "zeitgutschrift/<int:pk>/pdf/",
        views.zeitgutschrift_pdf,
        name="zeitgutschrift_pdf",
    ),
    path(
        "zeitgutschrift/felder/",
        views.zeitgutschrift_felder,
        name="zeitgutschrift_felder",
    ),
    path(
        "zeitgutschrift/neue-zeile/",
        views.neue_zeitgutschrift_zeile,
        name="neue_zeitgutschrift_zeile",
    ),
    path(
        "zeitgutschrift/fortbildung-berechnen/",
        views.zeitgutschrift_fortbildung_berechnen,
        name="zeitgutschrift_fortbildung_berechnen",
    ),
    # Genehmigungsworkflow
    path(
        "genehmigung/",
        views.genehmigung_uebersicht,
        name="genehmigung_uebersicht",
    ),
    path(
        "genehmigung/<str:antrag_typ>/<int:pk>/entscheiden/",
        views.genehmigung_entscheiden,
        name="genehmigung_entscheiden",
    ),
    # Dienstreise
    path(
        "dienstreise/erstellen/",
        views.dienstreise_erstellen,
        name="dienstreise_erstellen",
    ),
    path(
        "dienstreise/<int:pk>/bearbeiten/",
        views.dienstreise_bearbeiten,
        name="dienstreise_bearbeiten",
    ),
    path(
        "dienstreise/uebersicht/",
        views.dienstreise_uebersicht,
        name="dienstreise_uebersicht",
    ),
    path(
        "dienstreise/meine/",
        views.meine_dienstreisen,
        name="meine_dienstreisen",
    ),
    # Team-Queue-System
    path(
        "team-queue/",
        views_team_queue.team_queue_uebersicht,
        name="team_queue",
    ),
    path(
        "api/team-queues/",
        views.api_team_queues,
        name="api_team_queues",
    ),
    # Team-Builder
    path(
        "team-builder/",
        views.team_builder,
        name="team_builder",
    ),
    path(
        "team-builder/team/<int:pk>/",
        views.team_builder_detail,
        name="team_builder_detail",
    ),
    path(
        "team-builder/team/create/",
        views.team_builder_create,
        name="team_builder_create",
    ),
    path(
        "team-builder/team/<int:pk>/update/",
        views.team_builder_update,
        name="team_builder_update",
    ),
    path(
        "team-builder/team/<int:pk>/delete/",
        views.team_builder_delete,
        name="team_builder_delete",
    ),
    path(
        "team-builder/team/<int:pk>/member/add/",
        views.team_builder_add_member,
        name="team_builder_add_member",
    ),
    path(
        "team-builder/team/<int:pk>/member/remove/",
        views.team_builder_remove_member,
        name="team_builder_remove_member",
    ),
    path(
        "team-queue/antrag/<str:antrag_typ>/<int:pk>/",
        views_team_queue.antrag_detail,
        name="antrag_detail",
    ),
    path(
        "team-queue/claimen/<str:antrag_typ>/<int:pk>/",
        views_team_queue.antrag_claimen,
        name="antrag_claimen",
    ),
    path(
        "team-queue/freigeben/<str:antrag_typ>/<int:pk>/",
        views_team_queue.antrag_freigeben,
        name="antrag_freigeben",
    ),
    path(
        "team-queue/erledigen/<str:antrag_typ>/<int:pk>/",
        views_team_queue.antrag_erledigen,
        name="antrag_erledigen",
    ),
]
