# Generated by Django 6.0.1 on 2026-01-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schichtplan', '0002_alter_schichtwunsch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rolle', models.CharField(max_length=100)),
                ('schichtplan_kennung', models.CharField(blank=True, max_length=20, null=True)),
                ('aktiv', models.BooleanField(default=True)),
            ],
        ),
    ]
