# Generated by Django 6.0.1 on 2026-02-07 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schichtplan', '0005_remove_schichttausch_bearbeitet_am_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schichtplan',
            name='status',
            field=models.CharField(choices=[('entwurf', 'Entwurf'), ('zur_genehmigung', 'Zur Genehmigung'), ('veroeffentlicht', 'Veröffentlicht'), ('archiviert', 'Archiviert')], default='entwurf', max_length=20),
        ),
        migrations.AlterField(
            model_name='schichtwunsch',
            name='wunsch',
            field=models.CharField(choices=[('urlaub', '1 - Urlaub'), ('kein_tag_aber_nacht', '2 - Kein Tag, aber Nacht möglich'), ('keine_nacht_aber_tag', '3 - Keine Nacht, aber Tag möglich'), ('tag_bevorzugt', '4 - Tag bevorzugt'), ('nacht_bevorzugt', '5 - Nacht bevorzugt'), ('gar_nichts', '6 - Gar nichts möglich'), ('zusatzarbeit', '7 - Zusatzarbeit'), ('ausgleichstag', 'Z-AG Zeitausgleich'), ('krank', 'K Krank')], max_length=30),
        ),
        migrations.CreateModel(
            name='SchichtplanAenderung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('aktion', models.CharField(choices=[('angelegt', 'Schicht/Markierung angelegt'), ('geloescht', 'Schicht/Markierung gelöscht'), ('getauscht', 'Schichten getauscht'), ('bearbeitet', 'Schicht bearbeitet')], max_length=20)),
                ('beschreibung', models.CharField(max_length=400)),
                ('undo_daten', models.JSONField(blank=True, default=dict)),
                ('zurueckgenommen', models.BooleanField(default=False)),
                ('schichtplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aenderungsprotokoll', to='schichtplan.schichtplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schichtplan-Änderung',
                'verbose_name_plural': 'Schichtplan-Änderungen',
                'ordering': ['-zeit'],
            },
        ),
    ]
