# Generated by Django 6.0.2 on 2026-02-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schichtplan', '0006_add_schichtplan_aenderung'),
    ]

    operations = [
        migrations.AddField(
            model_name='schichtwunsch',
            name='ersatz_bestaetigt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schichtwunsch',
            name='ersatz_schichttyp',
            field=models.CharField(blank=True, choices=[('T', 'Tagschicht'), ('N', 'Nachtschicht')], default='', max_length=1),
        ),
    ]
