# Generated by Django 6.0.2 on 2026-02-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0014_mitarbeiter_telefon_alter_mitarbeiter_verfuegbarkeit'),
        ('schichtplan', '0007_schichtwunsch_ersatz_bestaetigt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schicht',
            name='ersatz_markierung',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schichtwunsch',
            name='ersatz_mitarbeiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ersatz_fuer_wuensche', to='arbeitszeit.mitarbeiter'),
        ),
    ]
