# Generated by Django 6.0.2 on 2026-02-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schichtplan', '0009_schichtplan_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schichtplansnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schichtplansnapshotschicht',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
