# Generated by Django 6.0.1 on 2026-02-14 14:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schichtplan', '0010_alter_schichtplansnapshot_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchichtplanKonfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_nummer', models.IntegerField(help_text='Auto-inkrementiert bei jeder neuen Config', unique=True)),
                ('bemerkung', models.TextField(blank=True, help_text='Was wurde geändert? (optional)')),
                ('aktiv', models.BooleanField(default=False, help_text='Nur die aktive Konfiguration wird für neue Pläne verwendet')),
                ('fairness_weight_tagschichten', models.IntegerField(default=2500, help_text='Tagsschichten-Ausgleich (höher = wichtiger)')),
                ('fairness_weight_nachtschichten', models.IntegerField(default=1500, help_text='Nachtschichten-Ausgleich')),
                ('fairness_weight_wochenenden', models.IntegerField(default=2000, help_text='Wochenend-Ausgleich')),
                ('wunsch_bonus_keine', models.IntegerField(default=5000, help_text='Bonus für 0 Wünsche (Maximum Kooperation)')),
                ('wunsch_bonus_wenige', models.IntegerField(default=3000, help_text='Bonus für wenige Wünsche (1-4)')),
                ('wunsch_bonus_mittel', models.IntegerField(default=1000, help_text='Bonus für mittlere Wünsche (5-14)')),
                ('wunsch_bonus_threshold_wenige', models.IntegerField(default=4, help_text="Threshold für 'wenig' Wünsche")),
                ('wunsch_bonus_threshold_mittel', models.IntegerField(default=14, help_text="Threshold für 'mittel' Wünsche")),
                ('wunsch_tag_bevorzugt', models.IntegerField(default=25000, help_text="Gewicht für 'Tag bevorzugt' Wunsch")),
                ('wunsch_nacht_bevorzugt', models.IntegerField(default=25000, help_text="Gewicht für 'Nacht bevorzugt' Wunsch")),
                ('wunsch_zusatzarbeit', models.IntegerField(default=5000, help_text="Gewicht für 'Zusatzarbeit' Wunsch")),
                ('wunsch_fixe_tagdienste', models.IntegerField(default=30000, help_text='Gewicht für fixe Tagdienst-Wochentage (MA1 Mi, etc.)')),
                ('wockenend_block_strafe', models.IntegerField(default=5000, help_text='MA7: Strafe wenn Nachtdienste nicht in 2er-Blöcken')),
                ('soll_stunden_abweichung_strafe', models.IntegerField(default=2000, help_text='Strafe für Abweichung vom Soll-Stunden-Ziel')),
                ('typ_b_overage_strafe', models.IntegerField(default=2000, help_text='Strafe für Schichten über Target (z.B. >6 Tagdienste)')),
                ('typ_b_min_erforderliche_tage', models.IntegerField(default=8, help_text='Min. verfügbare Tage für Typ B Constraint')),
                ('typ_b_min_tagschichten', models.IntegerField(default=4, help_text='Min. Tagschichten pro Monat (Typ B)')),
                ('typ_b_min_nachtschichten', models.IntegerField(default=4, help_text='Min. Nachtschichten pro Monat (Typ B)')),
                ('typ_b_target_tagschichten', models.IntegerField(default=6, help_text='Soft Target Tagschichten (üb 6 = Strafe)')),
                ('typ_b_target_nachtschichten', models.IntegerField(default=5, help_text='Soft Target Nachtschichten')),
                ('typ_b_max_schichten_bonus', models.IntegerField(default=6, help_text='Über diesen Wert: Strafe pro Schicht')),
                ('priority_multiplier_hoch', models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='High priority: Wünsche werden mit 1.5x gewichtet', max_digits=3)),
                ('priority_multiplier_niedrig', models.DecimalField(decimal_places=2, default=Decimal('0.8'), help_text='Low priority: Wünsche mit 0.8x gewichtet', max_digits=3)),
                ('solver_timeout_sekunden', models.IntegerField(default=300, help_text='Solver-Timeout in Sekunden (< 60s = suboptimal!)')),
                ('solver_num_workers', models.IntegerField(default=8, help_text='CPU-Worker für Parallelisierung')),
                ('solver_relative_gap_limit', models.DecimalField(decimal_places=3, default=Decimal('0.01'), help_text='Gap-Limit (0.01 = 1%)', max_digits=4)),
                ('solver_linearization_level', models.IntegerField(default=2, help_text='Linearisierungs-Tiefe (0-2)')),
                ('max_zusatzdienste_pro_tag', models.IntegerField(default=2, help_text='Max. Z-Dienste pro Kalendertag')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_konfigurationen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schichtplan-Konfiguration',
                'verbose_name_plural': 'Schichtplan-Konfigurationen',
                'ordering': ['-version_nummer'],
                'permissions': [('view_config_history', 'Kann Config-Historia anschauen'), ('change_scoring_weights', 'Darf Scoring-Gewichte ändern'), ('change_solver_parameters', 'Darf Solver-Parameter ändern')],
            },
        ),
        migrations.AddField(
            model_name='schichtplan',
            name='konfiguration',
            field=models.ForeignKey(blank=True, editable=False, help_text='Konfiguration, mit der dieser Plan erstellt wurde (Auto-gesetzt)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schichtplaene', to='schichtplan.schichtplankonfiguration'),
        ),
    ]
