# Generated by Django 6.0.1 on 2026-02-14 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schichtplan', '0011_schichtplankonfiguration_schichtplan_konfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalerFeiertag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="z.B. 'Rosenmontag', 'Aschermittwoch'", max_length=100, verbose_name='Feiertag-Name')),
                ('typ', models.CharField(choices=[('fest', 'Festes Datum (Monat + Tag)'), ('ostern_relativ', 'Relativ zu Ostern')], max_length=20, verbose_name='Datum-Typ')),
                ('region', models.CharField(choices=[('all', 'Alle Bundesländer'), ('nrw', 'Nordrhein-Westfalen'), ('bayern', 'Bayern'), ('bw', 'Baden-Württemberg'), ('hessen', 'Hessen'), ('niedersachsen', 'Niedersachsen')], default='all', max_length=20, verbose_name='Region/Bundesland')),
                ('monat', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Monat (1-12)')),
                ('tag', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Tag (1-31)')),
                ('ostern_offset', models.IntegerField(blank=True, help_text='z.B. -48 für Rosenmontag, +39 für Christi Himmelfahrt', null=True, verbose_name='Tage von Osternsonntag')),
                ('aktiv', models.BooleanField(default=True, help_text='Inaktive Feiertage werden nicht berücksichtigt', verbose_name='Aktiv')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regionaler Feiertag',
                'verbose_name_plural': 'Regionale Feiertage',
                'ordering': ['region', 'name'],
                'unique_together': {('name', 'region', 'typ')},
            },
        ),
    ]
