# Generated by Django 6.0.1 on 2026-02-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schichtplan', '0012_regionalerfeiertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='schichtplankonfiguration',
            name='tag_block_3er_strafe',
            field=models.IntegerField(default=1500, help_text='Penalty wenn 3 aufeinanderfolgende T-Schichten (z.B. Mo-Di-Mi). Default 1500.', verbose_name='Strafe für 3er Tagschicht-Blöcke'),
        ),
        migrations.AddField(
            model_name='schichtplankonfiguration',
            name='tag_block_4er_strafe',
            field=models.IntegerField(default=3000, help_text='Zusatz-Penalty für 4+ aufeinanderfolgende T-Schichten. Default 3000.', verbose_name='Strafe für 4er+ Tagschicht-Blöcke'),
        ),
    ]
