# Generated by Django 6.0.2 on 2026-02-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schichtplan', '0013_schichtplankonfiguration_tag_block_3er_strafe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schichtplan',
            options={'ordering': ['-start_datum'], 'permissions': [('schichtplan_zugang', 'Kann die Schichtplanung aufrufen')], 'verbose_name': 'Schichtplan', 'verbose_name_plural': 'Schichtpläne'},
        ),
    ]
