# Generated by Django 6.0.3 on 2026-03-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersthelfe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erstehilfevorfall',
            name='ort',
            field=models.CharField(help_text='Wo ist der Notfall? (z.B. Buero 2.OG, Kantine, Parkplatz)', max_length=200, verbose_name='Ort'),
        ),
    ]
