# Generated by Django 6.0.3 on 2026-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersthelfe', '0003_matrix_polling_felder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erstehilfeersthelfertoken',
            name='matrix_dm_room_id',
            field=models.CharField(blank=True, help_text='Raum-ID des persoenlichen DM-Chats (fuer Antworten-Polling)', max_length=200, verbose_name='Matrix-DM-Raum-ID'),
        ),
        migrations.AlterField(
            model_name='erstehilfeersthelfertoken',
            name='matrix_dm_since_token',
            field=models.CharField(blank=True, help_text='Pagination-Token fuer DM-Antworten-Polling', max_length=500, verbose_name='Matrix-DM Since-Token'),
        ),
        migrations.AlterField(
            model_name='erstehilfevorfall',
            name='matrix_ping_event_id',
            field=models.CharField(blank=True, help_text='Event-ID der Alarmnachricht im EH_PING-Raum (fuer Reaktionen-Polling)', max_length=200, verbose_name='Matrix EH_PING Event-ID'),
        ),
        migrations.AlterField(
            model_name='erstehilfevorfall',
            name='matrix_ping_since_token',
            field=models.CharField(blank=True, help_text='Pagination-Token fuer Reaktionen-Polling', max_length=500, verbose_name='Matrix EH_PING Since-Token'),
        ),
    ]
