# Generated by Django 6.0.3 on 2026-03-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ersthelfe', '0006_erstehilfenachricht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erstehilferueckmeldung',
            name='status',
            field=models.CharField(choices=[('unterwegs', 'Bin unterwegs'), ('am_ort', 'Bin vor Ort'), ('brauche_unterstuetzung', 'Brauche Unterstuetzung'), ('nicht_verfuegbar', 'Kann nicht kommen'), ('brauche_defi', 'Brauche Defibrillator'), ('brauche_rtw', 'Bitte RTW verstaendigen (112)'), ('brauche_zweiten_eh', 'Brauche zweiten Ersthelfer'), ('brauche_material', 'Brauche Verbandsmaterial'), ('patient_transportfaehig', 'Patient transportfaehig'), ('einsatz_beendet', 'Einsatz beendet / kein Arzt noetig')], max_length=30, verbose_name='Status'),
        ),
    ]
