# Generated by Django 6.0.3 on 2026-03-08 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0009_personalstammdaten'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anforderungen', models.TextField(blank=True, help_text='Was bringen Bewerber/innen idealerweise mit?', verbose_name='Anforderungen')),
                ('aufgaben', models.TextField(blank=True, help_text='Was erwartet die Person in dieser Stelle?', verbose_name='Aufgaben & Verantwortlichkeiten')),
                ('beschaeftigungsart', models.CharField(choices=[('vollzeit', 'Vollzeit'), ('teilzeit', 'Teilzeit'), ('beide', 'Vollzeit oder Teilzeit')], default='vollzeit', max_length=10, verbose_name='Beschaeftigungsart')),
                ('beschreibung', models.TextField(help_text='Uebersicht zur Stelle und zum Team (Blog-Stil).', verbose_name='Stellenbeschreibung')),
                ('bewerbungsfrist', models.DateField(blank=True, help_text='Leer lassen fuer offenes Ende.', null=True, verbose_name='Bewerbungsfrist')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('pausiert', 'Pausiert'), ('besetzt', 'Besetzt'), ('archiviert', 'Archiviert')], default='aktiv', max_length=10, verbose_name='Status')),
                ('titel', models.CharField(max_length=200, verbose_name='Stellentitel')),
                ('veroeffentlicht', models.BooleanField(default=False, help_text='Nur veroeffentlichte Ausschreibungen sind fuer Mitarbeiter sichtbar.', verbose_name='Veroeffentlicht')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_ausschreibungen', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('orgeinheit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausschreibungen', to='hr.orgeinheit', verbose_name='Organisationseinheit')),
                ('stelle', models.ForeignKey(blank=True, help_text='Die konkrete Planstelle, die besetzt werden soll.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausschreibungen', to='hr.stelle', verbose_name='Stelle')),
            ],
            options={
                'verbose_name': 'Ausschreibung',
                'verbose_name_plural': 'Ausschreibungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Bewerbung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('hr_notiz', models.TextField(blank=True, help_text='Nur fuer HR sichtbar – erscheint nicht beim Bewerber.', verbose_name='HR-Notiz (intern)')),
                ('motivationstext', models.TextField(verbose_name='Motivationstext')),
                ('status', models.CharField(choices=[('eingegangen', 'Eingegangen'), ('sichtung', 'In Pruefung'), ('gespraech', 'Vorstellungsgespraech'), ('angeboten', 'Angebot unterbreitet'), ('abgesagt', 'Abgesagt'), ('zurueckgezogen', 'Zurueckgezogen')], default='eingegangen', max_length=20, verbose_name='Status')),
                ('ausschreibung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewerbungen', to='stellenportal.ausschreibung', verbose_name='Ausschreibung')),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stellenbewerbungen', to=settings.AUTH_USER_MODEL, verbose_name='Bewerber/in')),
            ],
            options={
                'verbose_name': 'Bewerbung',
                'verbose_name_plural': 'Bewerbungen',
                'ordering': ['-erstellt_am'],
                'unique_together': {('ausschreibung', 'bewerber')},
            },
        ),
    ]
