# Generated by Django 6.0.2 on 2026-03-07 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0009_personalstammdaten'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bewerbung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau'), ('divers', 'Divers'), ('keine', 'Keine Angabe')], default='keine', max_length=10, verbose_name='Anrede')),
                ('vorname', models.CharField(max_length=100, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=100, verbose_name='Nachname')),
                ('geburtsname', models.CharField(blank=True, max_length=100, verbose_name='Geburtsname')),
                ('geburtsdatum', models.DateField(verbose_name='Geburtsdatum')),
                ('geburtsort', models.CharField(max_length=100, verbose_name='Geburtsort')),
                ('staatsangehoerigkeit', models.CharField(default='deutsch', max_length=50, verbose_name='Staatsangehoerigkeit')),
                ('familienstand', models.CharField(blank=True, choices=[('ledig', 'Ledig'), ('verheiratet', 'Verheiratet'), ('geschieden', 'Geschieden'), ('verwitwet', 'Verwitwet'), ('partnerschaft', 'Eingetragene Lebenspartnerschaft')], max_length=20, verbose_name='Familienstand')),
                ('konfession', models.CharField(blank=True, choices=[('evangelisch', 'Evangelisch'), ('katholisch', 'Katholisch'), ('keine', 'Keine / Sonstige')], max_length=20, verbose_name='Konfession')),
                ('anzahl_kinder', models.PositiveSmallIntegerField(default=0, verbose_name='Anzahl Kinder')),
                ('strasse', models.CharField(max_length=100, verbose_name='Strasse')),
                ('hausnummer', models.CharField(max_length=10, verbose_name='Hausnummer')),
                ('plz', models.CharField(max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(max_length=100, verbose_name='Wohnort')),
                ('land', models.CharField(default='Deutschland', max_length=50, verbose_name='Land')),
                ('telefon_privat', models.CharField(blank=True, max_length=30, verbose_name='Telefon privat')),
                ('mobil_privat', models.CharField(max_length=30, verbose_name='Mobil')),
                ('email_privat', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail privat')),
                ('steuerklasse', models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI')], max_length=1, verbose_name='Steuerklasse')),
                ('steuer_id', models.CharField(blank=True, max_length=11, verbose_name='Steuer-ID')),
                ('sozialversicherungsnummer', models.CharField(blank=True, max_length=12, verbose_name='Sozialversicherungsnummer')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Kreditinstitut')),
                ('krankenkasse_name', models.CharField(blank=True, max_length=100, verbose_name='Krankenkasse')),
                ('krankenversicherungsart', models.CharField(blank=True, choices=[('gesetzlich', 'Gesetzlich versichert'), ('privat', 'Privat versichert')], max_length=15, verbose_name='Versicherungsart')),
                ('notfallkontakt_name', models.CharField(blank=True, max_length=100, verbose_name='Notfallkontakt')),
                ('notfallkontakt_beziehung', models.CharField(blank=True, max_length=50, verbose_name='Beziehung')),
                ('notfallkontakt_telefon', models.CharField(blank=True, max_length=30, verbose_name='Telefon Notfallkontakt')),
                ('geplantes_eintrittsdatum', models.DateField(blank=True, null=True, verbose_name='Geplantes Eintrittsdatum')),
                ('vertragsart', models.CharField(blank=True, choices=[('unbefristet', 'Unbefristet'), ('befristet', 'Befristet'), ('minijob', 'Minijob'), ('praktikum', 'Praktikum / Ausbildung')], max_length=15, verbose_name='Vertragsart')),
                ('probezeit_bis', models.DateField(blank=True, null=True, verbose_name='Probezeit bis')),
                ('interne_notiz', models.TextField(blank=True, help_text='Nur fuer HR sichtbar, wird bei Ablehnung mitgeloescht.', verbose_name='Interne Notiz (HR)')),
                ('status', models.CharField(choices=[('neu', 'Neu eingegangen'), ('pruefung', 'In Pruefung (HR)'), ('eingestellt', 'Eingestellt'), ('abgelehnt', 'Abgelehnt')], default='neu', max_length=15, verbose_name='Status')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geaendert am')),
                ('angestrebte_stelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bewerbungen', to='hr.stelle', verbose_name='Angestrebte Stelle')),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bearbeitete_bewerbungen', to=settings.AUTH_USER_MODEL, verbose_name='Bearbeitet von (HR)')),
            ],
            options={
                'verbose_name': 'Bewerbung',
                'verbose_name_plural': 'Bewerbungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='BewerbungDokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('ausweis', 'Personalausweis / Reisepass'), ('zeugnis_schule', 'Schulzeugnis'), ('zeugnis_arbeit', 'Arbeitszeugnis'), ('abschluss', 'Abschlusszeugnis / Zertifikat'), ('fuehrerschein', 'Fuehrerschein'), ('sonstige', 'Sonstiges Dokument')], max_length=20, verbose_name='Dokumenttyp')),
                ('dateiname', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('dateityp', models.CharField(max_length=100, verbose_name='MIME-Typ')),
                ('inhalt_verschluesselt', models.BinaryField(verbose_name='Inhalt (verschluesselt)')),
                ('groesse_bytes', models.IntegerField(verbose_name='Dateigroesse (Bytes)')),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('bewerbung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='bewerbung.bewerbung', verbose_name='Bewerbung')),
            ],
            options={
                'verbose_name': 'Bewerbungsdokument',
                'verbose_name_plural': 'Bewerbungsdokumente',
                'ordering': ['typ', 'dateiname'],
            },
        ),
    ]
