# Generated by Django 6.0.3 on 2026-03-08 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewerbung',
            name='status',
            field=models.CharField(choices=[('eingegangen', 'Eingegangen'), ('faktencheck', 'Faktencheck'), ('gespraech_eingeladen', 'Zu Gespraech eingeladen'), ('tauglichkeitstest', 'Tauglichkeitstest'), ('zusage', 'Zusage erteilt'), ('abgelehnt', 'Abgelehnt')], default='eingegangen', max_length=22, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='EinladungsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Code')),
                ('status', models.CharField(choices=[('verfuegbar', 'Verfuegbar'), ('ausgegeben', 'Ausgegeben (noch nicht benutzt)'), ('verwendet', 'Verwendet')], default='verfuegbar', max_length=12, verbose_name='Status')),
                ('ausgegeben_an_name', models.CharField(blank=True, max_length=100, verbose_name='Ausgegeben an (Name)')),
                ('ausgegeben_an_telefon', models.CharField(blank=True, max_length=30, verbose_name='Ausgegeben an (Telefon)')),
                ('ausgegeben_am', models.DateTimeField(blank=True, null=True, verbose_name='Ausgegeben am')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('ausgegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausgegebene_codes', to=settings.AUTH_USER_MODEL, verbose_name='Ausgegeben von (HR)')),
            ],
            options={
                'verbose_name': 'Einladungscode',
                'verbose_name_plural': 'Einladungscodes',
                'ordering': ['status', 'code'],
            },
        ),
        migrations.AddField(
            model_name='bewerbung',
            name='einladungscode',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bewerbung', to='bewerbung.einladungscode', verbose_name='Einladungscode'),
        ),
    ]
