# Generated by Django 6.0.3 on 2026-03-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bewerbung', '0002_alter_bewerbung_status_einladungscode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewerbung',
            name='status',
            field=models.CharField(choices=[('eingegangen', 'Eingegangen'), ('faktencheck', 'Faktencheck'), ('tauglichkeitstest', 'Tauglichkeitstest'), ('zusage', 'Zusage erteilt'), ('abgelehnt', 'Abgelehnt')], default='eingegangen', max_length=22, verbose_name='Status'),
        ),
    ]
