# Generated by Django 6.0.3 on 2026-03-14 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_dms_archiv_abteilung'),
        ('matrix_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixraum',
            name='ping_typ',
            field=models.CharField(blank=True, choices=[('allgemein', 'Allgemein'), ('facility', 'Facility / Stoermeldungen'), ('hr', 'HR / Personal'), ('it', 'IT / Technik'), ('sicherheit', 'Sicherheit')], default='', help_text='Nur relevant wenn Typ = Ping-Kanal.', max_length=20, verbose_name='Ping-Kanal-Typ'),
        ),
        migrations.AlterField(
            model_name='sitzungskalender',
            name='ende_datum',
            field=models.DateField(blank=True, help_text='Leer = laeuft unbegrenzt.', null=True, verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='sitzungskalender',
            name='wochentag',
            field=models.IntegerField(blank=True, choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], help_text='Nur bei wiederkehrenden Sitzungen.', null=True, verbose_name='Wochentag'),
        ),
        migrations.AlterField(
            model_name='teilnehmertemplate',
            name='org_einheit',
            field=models.ForeignKey(blank=True, help_text='Alle Mitglieder dieser Einheit werden automatisch eingeladen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix_templates', to='hr.orgeinheit', verbose_name='Org-Einheit'),
        ),
    ]
