# Generated by Django 6.0.3 on 2026-03-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_dms_archiv_abteilung'),
        ('matrix_integration', '0002_alter_matrixraum_ping_typ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JitsiRaum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(blank=True)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Anzeigename')),
                ('raum_slug', models.SlugField(help_text="Wird Teil der Meeting-URL, z.B. 'teammeeting-it' -> meet.georg-klein.com/teammeeting-it", max_length=100, unique=True, verbose_name='Raum-Slug')),
                ('org_einheit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jitsi_raeume', to='hr.orgeinheit', verbose_name='Org-Einheit')),
            ],
            options={
                'verbose_name': 'Jitsi-Raum',
                'verbose_name_plural': 'Jitsi-Raeume',
                'ordering': ['name'],
            },
        ),
    ]
