# Generated by Django 6.0.3 on 2026-03-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_integration', '0003_jitsiraum'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitzungskalender',
            name='erinnerung_gesendet_am',
            field=models.DateTimeField(blank=True, help_text='Wird automatisch gesetzt nachdem die Erinnerung gesendet wurde.', null=True, verbose_name='Erinnerung gesendet am'),
        ),
    ]
