# Generated by Django 6.0.3 on 2026-03-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_integration', '0004_sitzungskalender_erinnerung_gesendet_am'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixraum',
            name='ping_typ',
            field=models.CharField(blank=True, choices=[('allgemein', 'Allgemein'), ('facility', 'Facility / Stoermeldungen (allgemein)'), ('fm_elektro', 'FM-Team Elektro'), ('fm_maler', 'FM-Team Maler'), ('fm_sanitaer', 'FM-Team Sanitaer / Heizung'), ('fm_schlosser', 'FM-Team Schlosser'), ('fm_schreiner', 'FM-Team Schreiner'), ('hr', 'HR / Personal'), ('it', 'IT / Technik'), ('sicherheit', 'Sicherheit')], default='', help_text='Nur relevant wenn Typ = Ping-Kanal.', max_length=20, verbose_name='Ping-Kanal-Typ'),
        ),
    ]
