# Generated by Django 6.0.2 on 2026-02-19 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kuerzel', models.CharField(max_length=10, unique=True)),
                ('beschreibung', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereiche',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Abteilung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kuerzel', models.CharField(max_length=10)),
                ('bereich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abteilungen', to='hr.bereich')),
            ],
            options={
                'verbose_name': 'Abteilung',
                'verbose_name_plural': 'Abteilungen',
                'ordering': ['bereich', 'name'],
                'unique_together': {('bereich', 'kuerzel')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abteilung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='hr.abteilung')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['abteilung', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HRMitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('personalnummer', models.CharField(max_length=20, unique=True)),
                ('rolle', models.CharField(choices=[('gf', 'Geschaeftsfuehrung'), ('bereichsleiter', 'Bereichsleiter/in'), ('abteilungsleiter', 'Abteilungsleiter/in'), ('assistent', 'Assistent/in (Stellvertretung)'), ('teamleiter', 'Teamleiter/in'), ('mitarbeiter', 'Mitarbeiter/in')], default='mitarbeiter', max_length=20)),
                ('eintrittsdatum', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('abteilung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitarbeiter', to='hr.abteilung')),
                ('bereich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitarbeiter', to='hr.bereich')),
                ('stellvertretung_fuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stellvertreter', to='hr.hrmitarbeiter', verbose_name='Stellvertretung fuer')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_mitarbeiter', to=settings.AUTH_USER_MODEL)),
                ('vorgesetzter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direkte_berichte', to='hr.hrmitarbeiter', verbose_name='Vorgesetzter/Vorgesetzte')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitarbeiter', to='hr.team')),
            ],
            options={
                'verbose_name': 'HR-Mitarbeiter',
                'verbose_name_plural': 'HR-Mitarbeiter',
                'ordering': ['nachname', 'vorname'],
                'permissions': [('genehmigen_antraege', 'Kann Antraege genehmigen/ablehnen'), ('view_zeiterfassung', 'Kann Zeiterfassung einsehen'), ('view_stammdaten', 'Kann Stammdaten einsehen')],
            },
        ),
    ]
