# Generated by Django 6.0.2 on 2026-02-20 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_orgeinheit_stelle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgeinheit',
            name='ist_reserviert',
            field=models.BooleanField(default=False, help_text='Reservierte Einheiten werden per Migration angelegt und sollten nicht geloescht werden.'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='delegiert_an',
            field=models.ForeignKey(blank=True, help_text='Massengeschaeft dauerhaft an diese Stelle delegiert.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erhaelt_delegation', to='hr.stelle', verbose_name='Delegiert an'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='max_urlaubstage_genehmigung',
            field=models.PositiveIntegerField(default=0, help_text='0 = unbegrenzt; darueber hinaus automatische Eskalation.', verbose_name='Max. Urlaubstage Genehmigung'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='vertretung_bis',
            field=models.DateField(blank=True, null=True, verbose_name='Vertretung bis'),
        ),
        migrations.AlterField(
            model_name='stelle',
            name='vertretung_von',
            field=models.DateField(blank=True, null=True, verbose_name='Vertretung von'),
        ),
        migrations.CreateModel(
            name='HierarchieSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snapshot_data', models.JSONField(help_text='JSON mit OrgEinheiten und Stellen Hierarchie', verbose_name='Snapshot-Daten')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Hierarchie-Snapshot',
                'verbose_name_plural': 'Hierarchie-Snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
