# Generated by Django 6.0.2 on 2026-02-22 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_orgeinheit_ist_reserviert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgeinheit',
            name='leitende_stelle',
            field=models.ForeignKey(blank=True, help_text='Die Stelle, die diese OrgEinheit leitet (z.B. Bereichsleiter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geleitete_orgeinheiten', to='hr.stelle', verbose_name='Leitende Stelle'),
        ),
    ]
