# Generated by Django 6.0.2 on 2026-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_orgeinheit_leitende_stelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='stelle',
            name='kategorie',
            field=models.CharField(choices=[('leitung', 'Leitung'), ('stab', 'Stab'), ('fachkraft', 'Fachkraft')], default='fachkraft', help_text='Leitungsstellen werden im Organigramm besonders hervorgehoben.', max_length=20, verbose_name='Kategorie'),
        ),
    ]
