# Generated by Django 6.0.2 on 2026-02-22 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_stelle_kategorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projektgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name der Projektgruppe', max_length=200, verbose_name='Projektname')),
                ('kuerzel', models.CharField(help_text='Eindeutiges Kuerzel (z.B. PROJ-2025-01)', max_length=20, unique=True, verbose_name='Kuerzel')),
                ('beschreibung', models.TextField(blank=True, help_text='Ziele und Aufgaben', verbose_name='Beschreibung')),
                ('start_datum', models.DateField(help_text='Projektstart', verbose_name='Startdatum')),
                ('end_datum', models.DateField(blank=True, help_text='Geplantes Projektende', null=True, verbose_name='Enddatum (geplant)')),
                ('tatsaechliches_end_datum', models.DateField(blank=True, help_text='Tatsaechliches Projektende', null=True, verbose_name='Enddatum (tatsaechlich)')),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('abgeschlossen', 'Abgeschlossen'), ('pausiert', 'Pausiert'), ('abgebrochen', 'Abgebrochen')], default='aktiv', max_length=20, verbose_name='Status')),
                ('prioritaet', models.IntegerField(default=5, help_text='1 = hoechste Prioritaet, 10 = niedrigste', verbose_name='Prioritaet')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_projekte', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('leiter', models.ForeignKey(help_text='Verantwortliche Person fuer dieses Projekt', on_delete=django.db.models.deletion.PROTECT, related_name='geleitete_projekte', to='hr.hrmitarbeiter', verbose_name='Projektleiter/in')),
                ('mitglieder', models.ManyToManyField(blank=True, help_text='Alle Projektmitglieder', related_name='projektgruppen', to='hr.hrmitarbeiter', verbose_name='Mitglieder')),
                ('stellvertreter', models.ForeignKey(blank=True, help_text='Vertretung bei Abwesenheit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stellvertretende_projekte', to='hr.hrmitarbeiter', verbose_name='Stellvertreter/in')),
            ],
            options={
                'verbose_name': 'Projektgruppe',
                'verbose_name_plural': 'Projektgruppen',
                'ordering': ['-prioritaet', 'start_datum'],
            },
        ),
    ]
