# Generated by Django 6.0.2 on 2026-03-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_projektgruppe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmitarbeiter',
            name='personalnummer',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
