# Generated by Django 6.0.2 on 2026-03-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_hrmitarbeiter_personalnummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmitarbeiter',
            name='durchwahl',
            field=models.CharField(blank=True, help_text='Interne Telefondurchwahl (z.B. 4201)', max_length=10, verbose_name='Durchwahl'),
        ),
    ]
