# Generated by Django 6.0.2 on 2026-03-07 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_add_durchwahl_to_hrmitarbeiter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalstammdaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau'), ('divers', 'Divers'), ('keine', 'Keine Angabe')], default='keine', max_length=10, verbose_name='Anrede')),
                ('geburtsdatum', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('geburtsort', models.CharField(blank=True, max_length=100, verbose_name='Geburtsort')),
                ('geburtsname', models.CharField(blank=True, help_text='Falls abweichend vom aktuellen Nachnamen', max_length=100, verbose_name='Geburtsname')),
                ('staatsangehoerigkeit', models.CharField(blank=True, default='deutsch', max_length=50, verbose_name='Staatsangehoerigkeit')),
                ('familienstand', models.CharField(blank=True, choices=[('ledig', 'Ledig'), ('verheiratet', 'Verheiratet'), ('geschieden', 'Geschieden'), ('verwitwet', 'Verwitwet'), ('partnerschaft', 'Eingetragene Lebenspartnerschaft')], max_length=20, verbose_name='Familienstand')),
                ('konfession', models.CharField(blank=True, choices=[('evangelisch', 'Evangelisch'), ('katholisch', 'Katholisch'), ('keine', 'Keine / Sonstige')], help_text='Relevant fuer Kirchensteuer', max_length=20, verbose_name='Konfession')),
                ('anzahl_kinder', models.PositiveSmallIntegerField(default=0, verbose_name='Anzahl Kinder')),
                ('strasse', models.CharField(blank=True, max_length=100, verbose_name='Strasse')),
                ('hausnummer', models.CharField(blank=True, max_length=10, verbose_name='Hausnummer')),
                ('plz', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Wohnort')),
                ('land', models.CharField(blank=True, default='Deutschland', max_length=50, verbose_name='Land')),
                ('telefon_privat', models.CharField(blank=True, max_length=30, verbose_name='Telefon privat')),
                ('mobil_privat', models.CharField(blank=True, max_length=30, verbose_name='Mobil privat')),
                ('email_privat', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail privat')),
                ('steuerklasse', models.CharField(blank=True, choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI')], max_length=1, verbose_name='Steuerklasse')),
                ('steuer_id', models.CharField(blank=True, help_text='11-stellige Steuer-ID (Bundeszentralamt)', max_length=11, verbose_name='Steuer-Identifikationsnummer')),
                ('sozialversicherungsnummer', models.CharField(blank=True, max_length=12, verbose_name='Sozialversicherungsnummer')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Kreditinstitut')),
                ('krankenkasse_name', models.CharField(blank=True, max_length=100, verbose_name='Krankenkasse')),
                ('krankenversicherungsart', models.CharField(blank=True, choices=[('gesetzlich', 'Gesetzlich versichert'), ('privat', 'Privat versichert')], max_length=15, verbose_name='Versicherungsart')),
                ('notfallkontakt_name', models.CharField(blank=True, max_length=100, verbose_name='Notfallkontakt Name')),
                ('notfallkontakt_beziehung', models.CharField(blank=True, help_text='z.B. Ehepartner, Elternteil', max_length=50, verbose_name='Beziehung')),
                ('notfallkontakt_telefon', models.CharField(blank=True, max_length=30, verbose_name='Notfallkontakt Telefon')),
                ('vertragsart', models.CharField(blank=True, choices=[('unbefristet', 'Unbefristet'), ('befristet', 'Befristet'), ('minijob', 'Minijob'), ('praktikum', 'Praktikum / Ausbildung')], max_length=15, verbose_name='Vertragsart')),
                ('probezeit_bis', models.DateField(blank=True, null=True, verbose_name='Probezeit bis')),
                ('austrittsdatum', models.DateField(blank=True, null=True, verbose_name='Austrittsdatum')),
                ('angelegt_am', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='Geaendert am')),
                ('angelegt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='angelegte_stammdaten', to=settings.AUTH_USER_MODEL, verbose_name='Angelegt von')),
                ('mitarbeiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stammdaten', to='hr.hrmitarbeiter', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Personalstammdaten',
                'verbose_name_plural': 'Personalstammdaten',
                'permissions': [('hr_view_stammdaten', 'Kann sensible Personalstammdaten einsehen'), ('hr_change_stammdaten', 'Kann sensible Personalstammdaten bearbeiten')],
            },
        ),
    ]
