# Generated by Django 6.0.3 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_brandschutz_felder'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmitarbeiter',
            name='matrix_bot_dm_room_id',
            field=models.CharField(blank=True, help_text='Persistente DM-Raum-ID zwischen prima-bot und diesem Mitarbeiter (wird automatisch gesetzt)', max_length=200, verbose_name='Matrix-Bot-DM-Raum'),
        ),
    ]
