# Generated by Django 6.0.3 on 2026-03-22 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_add_matrix_bot_dm_room_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StammdatenAenderungsMeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felder_geaendert', models.JSONField(default=list, help_text='Liste der abweichenden Felder: [{feld, stammdaten_wert, nutzer_wert}]')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('bearbeitet', models.BooleanField(default=False)),
                ('bearbeitet_am', models.DateTimeField(blank=True, null=True)),
                ('notiz', models.TextField(blank=True)),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bearbeitete_stammdaten_meldungen', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stammdaten_meldungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stammdaten-Aenderungsmeldung',
                'verbose_name_plural': 'Stammdaten-Aenderungsmeldungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(blank=True, max_length=100)),
                ('nachname', models.CharField(blank=True, max_length=100)),
                ('abteilung', models.CharField(blank=True, max_length=200)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
            },
        ),
    ]
