# Generated by Django 6.0.2 on 2026-03-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datenschutz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loeschprotokoll',
            name='kategorien',
            field=models.JSONField(default=dict, help_text='Dict: Kategoriename → Anzahl Datensaetze.', verbose_name='Geloeschte Datenkategorien'),
        ),
    ]
