# Generated by Django 6.0.3 on 2026-03-21 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField(default=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('schema_json', models.JSONField(default=dict)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstelle_schemata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formular-Schema',
                'verbose_name_plural': 'Formular-Schemata',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormularEintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten_json', models.JSONField(default=dict)),
                ('eingereicht_am', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('eingereicht', 'Eingereicht'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt'), ('abgelehnt', 'Abgelehnt')], default='eingereicht', max_length=20)),
                ('eingereicht_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formular_eintraege', to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eintraege', to='prozesse.formularschema')),
            ],
            options={
                'verbose_name': 'Formular-Eintrag',
                'verbose_name_plural': 'Formular-Eintraege',
                'ordering': ['-eingereicht_am'],
            },
        ),
    ]
