# Generated by Django 6.0.3 on 2026-03-22 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prozesse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeldGruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('felder_json', models.JSONField(default=dict)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstelle_feldgruppen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feld-Baustein',
                'verbose_name_plural': 'Feld-Bausteine',
                'ordering': ['name'],
            },
        ),
    ]
