# Generated by Django 6.0.3 on 2026-03-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prozesse', '0002_feldgruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularschema',
            name='sichtbarkeit',
            field=models.CharField(choices=[('intern', 'Intern (Login erforderlich)'), ('extern', 'Extern (oeffentlich, Kiosk)')], default='intern', max_length=10, verbose_name='Sichtbarkeit'),
        ),
    ]
