# Generated by Django 6.0.3 on 2026-03-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prozesse', '0003_sichtbarkeit_extern'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulareintrag',
            name='paperless_dokument_id',
            field=models.IntegerField(blank=True, help_text='Wird gesetzt wenn ein physisch unterschriebenes Dokument in Paperless erkannt wurde.', null=True, verbose_name='Paperless-Dokument-ID'),
        ),
        migrations.AddField(
            model_name='formulareintrag',
            name='vorgangsnummer',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Vorgangsnummer'),
        ),
        migrations.AddField(
            model_name='formularschema',
            name='kuerzel',
            field=models.CharField(blank=True, help_text='2-6 Grossbuchstaben, z.B. HUN fuer Hundesteuer. Wird fuer Vorgangsnummern verwendet.', max_length=6, verbose_name='Kürzel'),
        ),
    ]
