# Generated by Django 6.0.3 on 2026-03-18 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupProtokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('backup', 'Datensicherung'), ('restore_test', 'Restore-Test')], max_length=20, verbose_name='Typ')),
                ('status', models.CharField(choices=[('laufend', 'Laufend'), ('ok', 'Erfolgreich'), ('fehler', 'Fehlgeschlagen')], default='laufend', max_length=20, verbose_name='Status')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Gestartet am')),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('dateiname', models.CharField(blank=True, max_length=300, verbose_name='Dateiname')),
                ('dateigroesse_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Dateigroesse (Bytes)')),
                ('tabellen_anzahl', models.IntegerField(blank=True, null=True, verbose_name='Tabellen im Backup')),
                ('zeilen_gesamt', models.BigIntegerField(blank=True, null=True, verbose_name='Zeilen gesamt (Restore-Test)')),
                ('fehler_meldung', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ausgeloest von')),
            ],
            options={
                'verbose_name': 'Backup-Protokoll',
                'verbose_name_plural': 'Backup-Protokolle',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
