# Generated by Django 6.0.2 on 2026-02-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0006_projektgruppe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anmeldeschluss', models.DateField(blank=True, null=True, verbose_name='Anmeldeschluss')),
                ('art', models.CharField(choices=[('sommerfest', 'Sommerfest'), ('weihnachtsfeier', 'Weihnachtsfeier'), ('teamausflug', 'Teamausflug'), ('jubilaeum', 'Jubilaeum'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=30, verbose_name='Art der Veranstaltung')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('ort', models.CharField(blank=True, max_length=200, verbose_name='Ort')),
                ('reichweite', models.CharField(choices=[('abteilung', 'Abteilung'), ('bereich', 'Bereich'), ('unternehmen', 'Unternehmen')], default='abteilung', max_length=20, verbose_name='Reichweite')),
                ('status', models.CharField(choices=[('geplant', 'Geplant'), ('anmeldung_offen', 'Anmeldung offen'), ('anmeldung_geschlossen', 'Anmeldung geschlossen'), ('abgeschlossen', 'Abgeschlossen'), ('storniert', 'Storniert')], default='geplant', max_length=30, verbose_name='Status')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('uhrzeit_bis', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit bis')),
                ('uhrzeit_von', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit von')),
                ('gutschrift_faktor', models.DecimalField(decimal_places=2, default=1.0, help_text='Beispiel: 0.5 = halbe Vergütung der Veranstaltungsdauer', max_digits=4, verbose_name='Gutschrift-Faktor (Teilnehmer)')),
                ('gutschrift_stunden', models.DecimalField(decimal_places=2, default=0, help_text='Stunden die als Zeitgutschrift angerechnet werden.', max_digits=5, verbose_name='Gutschrift-Stunden (Teilnehmer)')),
                ('vorbereitung_faktor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Faktor (Vorbereitungsteam)')),
                ('vorbereitung_stunden', models.DecimalField(decimal_places=2, default=0, help_text='Separate Stunden für das Vorbereitungsteam.', max_digits=5, verbose_name='Stunden (Vorbereitungsteam)')),
                ('abteilung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veranstaltungen', to='hr.abteilung', verbose_name='Abteilung')),
                ('bereich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veranstaltungen', to='hr.bereich', verbose_name='Bereich')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_veranstaltungen', to='hr.hrmitarbeiter', verbose_name='Erstellt von')),
                ('verantwortlicher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verantwortete_veranstaltungen', to='hr.hrmitarbeiter', verbose_name='Verantwortlicher')),
            ],
            options={
                'verbose_name': 'Veranstaltung',
                'verbose_name_plural': 'Veranstaltungen',
                'ordering': ['-datum', 'titel'],
            },
        ),
        migrations.CreateModel(
            name='FeierteilnahmeGutschrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingereicht_am', models.DateTimeField(blank=True, null=True, verbose_name='Eingereicht am')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('eingereicht', 'Eingereicht'), ('bearbeitet', 'Bearbeitet'), ('abgelehnt', 'Abgelehnt')], default='entwurf', max_length=20, verbose_name='Status')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_gutschriften', to='hr.hrmitarbeiter', verbose_name='Erstellt von')),
                ('feier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gutschrift_dokument', to='veranstaltungen.feier', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Zeitgutschrift-Sammelliste',
                'verbose_name_plural': 'Zeitgutschrift-Sammellisten',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='FeierteilnahmeAnmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_gast', models.BooleanField(default=False, help_text='Externer Gast (kein Mitarbeiter).', verbose_name='Gast')),
                ('ist_vorbereitungsteam', models.BooleanField(default=False, verbose_name='Vorbereitungsteam')),
                ('angemeldet_am', models.DateTimeField(auto_now_add=True)),
                ('teilnahme_bestaetigt', models.BooleanField(default=False, verbose_name='Teilnahme bestaetigt')),
                ('bestaetigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Bestaetigt am')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('bestaetigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bestaetigte_anmeldungen', to='hr.hrmitarbeiter', verbose_name='Bestaetigt von')),
                ('feier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='veranstaltungen.feier', verbose_name='Veranstaltung')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veranstaltungsanmeldungen', to='hr.hrmitarbeiter', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Teilnahmeanmeldung',
                'verbose_name_plural': 'Teilnahmeanmeldungen',
                'ordering': ['feier', 'mitarbeiter'],
                'unique_together': {('feier', 'mitarbeiter')},
            },
        ),
    ]
