# Generated by Django 6.0.3 on 2026-03-14 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranstaltungen', '0001_initial'),
        ('workflow', '0014_add_ist_laufzettel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feierteilnahmegutschrift',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veranstaltungs_gutschriften', to='workflow.workflowinstance', verbose_name='Workflow-Instanz'),
        ),
    ]
