# Generated by Django 6.0.2 on 2026-03-04 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0007_alter_hrmitarbeiter_personalnummer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gebaeude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baujahr', models.IntegerField(blank=True, null=True)),
                ('bezeichnung', models.CharField(max_length=200)),
                ('kuerzel', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Gebaeude',
                'verbose_name_plural': 'Gebaeude',
                'ordering': ['standort', 'kuerzel'],
            },
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField(blank=True)),
                ('kuerzel', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Geschoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('kuerzel', models.CharField(choices=[('UG2', '2. Untergeschoss'), ('UG', 'Untergeschoss'), ('EG', 'Erdgeschoss'), ('1', '1. Obergeschoss'), ('2', '2. Obergeschoss'), ('3', '3. Obergeschoss'), ('4', '4. Obergeschoss'), ('5', '5. Obergeschoss'), ('DG', 'Dachgeschoss')], max_length=5)),
                ('reihenfolge', models.IntegerField(default=0)),
                ('gebaeude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geschosse', to='raumbuch.gebaeude')),
            ],
            options={
                'verbose_name': 'Geschoss',
                'verbose_name_plural': 'Geschosse',
                'ordering': ['gebaeude', 'reihenfolge'],
            },
        ),
        migrations.CreateModel(
            name='Bereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('kuerzel', models.CharField(blank=True, max_length=10)),
                ('geschoss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bereiche', to='raumbuch.geschoss')),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereiche',
                'ordering': ['geschoss', 'bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('flaeche_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('ist_leer', models.BooleanField(default=False)),
                ('kapazitaet', models.IntegerField(blank=True, null=True)),
                ('nutzungsmodell', models.CharField(choices=[('statisch', 'Statisch (dauerhaft belegt)'), ('dynamisch', 'Buchbar')], default='statisch', max_length=20)),
                ('raumname', models.CharField(blank=True, max_length=200)),
                ('raumnummer', models.CharField(max_length=20)),
                ('raumtyp', models.CharField(choices=[('einzelbuero', 'Einzelbuero'), ('grossraumbuero', 'Grossraumbuero'), ('teambuero', 'Teambuero'), ('homeoffice_pool', 'Homeoffice-Pool'), ('besprechung', 'Besprechungsraum'), ('konferenz', 'Konferenzraum'), ('schulung', 'Schulungsraum'), ('ideenraum', 'Ideenraum'), ('telefonbox', 'Telefonbox'), ('teekueche', 'Teekueche'), ('kantine', 'Kantine'), ('pausenraum', 'Pausenraum'), ('wc_herren', 'WC Herren'), ('wc_damen', 'WC Damen'), ('wc_barrierefrei', 'WC Barrierefrei'), ('dusche', 'Dusche'), ('serverraum', 'Serverraum'), ('it_verteiler', 'IT-Verteiler'), ('elektroverteilung', 'Elektroverteilung'), ('heizungsraum', 'Heizungsraum'), ('lueftungsraum', 'Lueftungsraum'), ('lager', 'Lager'), ('archiv', 'Archiv'), ('druckerraum', 'Druckerraum'), ('putzraum', 'Putzraum'), ('abstellraum', 'Abstellraum'), ('flur', 'Flur'), ('eingang', 'Eingang'), ('aufzug', 'Aufzug'), ('windfang', 'Windfang'), ('sonstiges', 'Sonstiges')], max_length=30)),
                ('bereich', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raeume', to='raumbuch.bereich')),
                ('geschoss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raeume', to='raumbuch.geschoss')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Raeume',
                'ordering': ['geschoss__reihenfolge', 'raumnummer'],
                'unique_together': {('geschoss', 'raumnummer')},
            },
        ),
        migrations.CreateModel(
            name='Besuchsanmeldung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besucher_firma', models.CharField(blank=True, max_length=200)),
                ('besucher_nachname', models.CharField(max_length=100)),
                ('besucher_vorname', models.CharField(max_length=100)),
                ('bis', models.TimeField(blank=True, null=True)),
                ('datum', models.DateField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('angemeldet', 'Angemeldet'), ('erschienen', 'Erschienen'), ('abgesagt', 'Abgesagt')], default='angemeldet', max_length=20)),
                ('von', models.TimeField(blank=True, null=True)),
                ('zweck', models.TextField(blank=True)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='besuchsanmeldungen', to=settings.AUTH_USER_MODEL)),
                ('gastgeber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='besuche', to='hr.hrmitarbeiter')),
                ('zielraum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='besuche', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Besuchsanmeldung',
                'verbose_name_plural': 'Besuchsanmeldungen',
                'ordering': ['-datum', 'von'],
            },
        ),
        migrations.CreateModel(
            name='Belegung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bis', models.DateField(blank=True, null=True)),
                ('notiz', models.TextField(blank=True)),
                ('von', models.DateField()),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raum_belegungen', to='hr.hrmitarbeiter')),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='belegungen', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Belegung',
                'verbose_name_plural': 'Belegungen',
                'ordering': ['-von'],
            },
        ),
        migrations.CreateModel(
            name='RaumArbeitsschutzDaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aed_standort', models.CharField(blank=True, max_length=200)),
                ('barrierefrei', models.BooleanField(default=False)),
                ('barrierefreiheit_details', models.TextField(blank=True)),
                ('brandabschnitt', models.CharField(blank=True, max_length=100)),
                ('erste_hilfe_kasten', models.BooleanField(default=False)),
                ('erste_hilfe_standort', models.CharField(blank=True, max_length=200)),
                ('feuerloesch_naechste_pruefung', models.DateField(blank=True, null=True)),
                ('feuerloesch_nummer', models.CharField(blank=True, max_length=50)),
                ('feuerloesch_typ', models.CharField(blank=True, max_length=100)),
                ('fluchtweg_beschreibung', models.TextField(blank=True)),
                ('gefahrstoffe_beschreibung', models.TextField(blank=True)),
                ('gefahrstoffe_vorhanden', models.BooleanField(default=False)),
                ('rauchmelder', models.BooleanField(default=False)),
                ('raum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arbeitsschutz_daten', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Arbeitsschutz-Daten',
                'verbose_name_plural': 'Arbeitsschutz-Daten',
            },
        ),
        migrations.CreateModel(
            name='RaumbuchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktion', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
                ('geaendert_am', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('objekt_id', models.IntegerField(blank=True, null=True)),
                ('geaendert_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('raum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_eintraege', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Raumbuch-Log',
                'verbose_name_plural': 'Raumbuch-Logs',
                'ordering': ['-geaendert_am'],
            },
        ),
        migrations.CreateModel(
            name='Raumbuchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betreff', models.CharField(max_length=200)),
                ('bis', models.TimeField()),
                ('buchungs_nr', models.CharField(max_length=20, unique=True)),
                ('datum', models.DateField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('offen', 'Ausstehend'), ('bestaetigt', 'Bestaetigt'), ('storniert', 'Storniert')], default='offen', max_length=20)),
                ('teilnehmerzahl', models.IntegerField(blank=True, null=True)),
                ('von', models.TimeField()),
                ('buchender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungen', to=settings.AUTH_USER_MODEL)),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungen', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Raumbuchung',
                'verbose_name_plural': 'Raumbuchungen',
                'ordering': ['-datum', 'von'],
            },
        ),
        migrations.CreateModel(
            name='RaumElektroDaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drehstrom', models.BooleanField(default=False)),
                ('notbeleuchtung', models.BooleanField(default=False)),
                ('sicherungsbezeichnungen', models.TextField(blank=True)),
                ('stromkreise_beschreibung', models.TextField(blank=True)),
                ('usv_gesichert', models.BooleanField(default=False)),
                ('raum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elektro_daten', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Elektro-Daten',
                'verbose_name_plural': 'Elektro-Daten',
            },
        ),
        migrations.CreateModel(
            name='RaumFacilityDaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baujahr', models.IntegerField(blank=True, null=True)),
                ('bodenbelag', models.CharField(blank=True, max_length=100)),
                ('fenster_anzahl', models.IntegerField(blank=True, null=True)),
                ('fenster_verdunkelbar', models.BooleanField(default=False)),
                ('flaeche_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('klima_typ', models.CharField(blank=True, max_length=100)),
                ('letzte_renovierung', models.DateField(blank=True, null=True)),
                ('lueftungsanlage', models.BooleanField(default=False)),
                ('moebelliste', models.TextField(blank=True)),
                ('volumen_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('raum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_daten', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Facility-Daten',
                'verbose_name_plural': 'Facility-Daten',
            },
        ),
        migrations.CreateModel(
            name='RaumInstallationDaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absperrhaehne', models.TextField(blank=True)),
                ('brandschutzklappen', models.TextField(blank=True)),
                ('glt_adressen', models.TextField(blank=True)),
                ('raum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation_daten', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Installations-Daten',
                'verbose_name_plural': 'Installations-Daten',
            },
        ),
        migrations.CreateModel(
            name='RaumNetzwerkDaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adressen', models.TextField(blank=True)),
                ('lan_ports_anzahl', models.IntegerField(blank=True, null=True)),
                ('lan_ports_beschreibung', models.TextField(blank=True)),
                ('switch_name', models.CharField(blank=True, max_length=100)),
                ('switch_port', models.CharField(blank=True, max_length=100)),
                ('telefondosen', models.IntegerField(blank=True, null=True)),
                ('wlan_abdeckung', models.CharField(blank=True, choices=[('gut', 'Gut'), ('mittel', 'Mittel'), ('schwach', 'Schwach'), ('keine', 'Keine')], max_length=10)),
                ('raum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='netzwerk_daten', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Netzwerk-Daten',
                'verbose_name_plural': 'Netzwerk-Daten',
            },
        ),
        migrations.CreateModel(
            name='Reinigungsplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervall', models.CharField(choices=[('taeglich', 'Taeglich'), ('woechentlich', 'Woechentlich'), ('monatlich', 'Monatlich'), ('nach_bedarf', 'Nach Bedarf')], default='taeglich', max_length=20)),
                ('letzte_reinigung', models.DateField(blank=True, null=True)),
                ('methode', models.CharField(blank=True, max_length=200)),
                ('zustaendig', models.CharField(blank=True, max_length=200)),
                ('raum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reinigungsplan', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Reinigungsplan',
                'verbose_name_plural': 'Reinigungsplaene',
            },
        ),
        migrations.CreateModel(
            name='ReinigungsQuittung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemerkung', models.TextField(blank=True)),
                ('quittiert_durch_name', models.CharField(max_length=200)),
                ('zeitstempel', models.DateTimeField(auto_now_add=True)),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinigungen', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Reinigungsquittung',
                'verbose_name_plural': 'Reinigungsquittungen',
                'ordering': ['-zeitstempel'],
            },
        ),
        migrations.CreateModel(
            name='Schluessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl_kopien', models.IntegerField(default=1)),
                ('bezeichnung', models.CharField(max_length=200)),
                ('schliessanlage', models.CharField(blank=True, max_length=100)),
                ('schliessanlage_typ', models.CharField(choices=[('general', 'Generalschluessel'), ('gruppe', 'Gruppenschluessel'), ('einzel', 'Einzelschluessel')], default='einzel', max_length=20)),
                ('schluesselnummer', models.CharField(max_length=50, unique=True)),
                ('raeume', models.ManyToManyField(blank=True, related_name='schluessel', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Schluessel',
                'verbose_name_plural': 'Schluessel',
                'ordering': ['schluesselnummer'],
            },
        ),
        migrations.CreateModel(
            name='SchluesselAusgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausgabe_datum', models.DateField()),
                ('bemerkung', models.TextField(blank=True)),
                ('rueckgabe_datum', models.DateField(blank=True, null=True)),
                ('ausgegeben_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausgaben_erstellt', to=settings.AUTH_USER_MODEL)),
                ('empfaenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schluessel_ausgaben', to='hr.hrmitarbeiter')),
                ('schluessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ausgaben', to='raumbuch.schluessel')),
            ],
            options={
                'verbose_name': 'Schluessel-Ausgabe',
                'verbose_name_plural': 'Schluessel-Ausgaben',
                'ordering': ['-ausgabe_datum'],
            },
        ),
        migrations.AddField(
            model_name='gebaeude',
            name='standort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gebaeude', to='raumbuch.standort'),
        ),
        migrations.CreateModel(
            name='Treppenhaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('kapazitaet_personen', models.IntegerField(blank=True, null=True)),
                ('letzter_begehungstermin', models.DateField(blank=True, null=True)),
                ('lichte_breite_cm', models.IntegerField(blank=True, null=True)),
                ('maengel', models.TextField(blank=True)),
                ('naechste_pruefung', models.DateField(blank=True, null=True)),
                ('typ', models.CharField(choices=[('haupt', 'Haupttreppenhaus'), ('neben', 'Nebentreppenhaus'), ('notausgang', 'Notausgang')], default='haupt', max_length=20)),
                ('verbindet_geschosse', models.CharField(blank=True, help_text='z.B. UG-4.OG', max_length=100)),
                ('zustand', models.CharField(choices=[('gut', 'Gut'), ('maengel', 'Maengel vorhanden'), ('kritisch', 'Kritisch')], default='gut', max_length=20)),
                ('gebaeude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treppenhaeuser', to='raumbuch.gebaeude')),
            ],
            options={
                'verbose_name': 'Treppenhaus',
                'verbose_name_plural': 'Treppenhaeuser',
                'ordering': ['gebaeude', 'bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Umzugsauftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_geplant', models.DateField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('notiz', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt'), ('storniert', 'Storniert')], default='offen', max_length=20)),
                ('beauftragt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='umzuege_beauftragt', to=settings.AUTH_USER_MODEL)),
                ('mitarbeiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umzuege', to='hr.hrmitarbeiter')),
                ('nach_raum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einzuege', to='raumbuch.raum')),
                ('von_raum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auszuege', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Umzugsauftrag',
                'verbose_name_plural': 'Umzugsauftraege',
                'ordering': ['datum_geplant'],
            },
        ),
        migrations.CreateModel(
            name='ZutrittsProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.TextField(blank=True)),
                ('bezeichnung', models.CharField(max_length=200)),
                ('raeume', models.ManyToManyField(blank=True, related_name='zutrittsprofile', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Zutrittsprofil',
                'verbose_name_plural': 'Zutrittsprofile',
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='ZutrittsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ablauf_warnung_tage', models.IntegerField(default=30)),
                ('ausgestellt_am', models.DateField()),
                ('badge_id', models.CharField(max_length=100)),
                ('bemerkung', models.TextField(blank=True)),
                ('gueltig_bis', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('gesperrt', 'Gesperrt'), ('verloren', 'Verloren')], default='aktiv', max_length=20)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zutritts_tokens', to='hr.hrmitarbeiter')),
                ('profile', models.ManyToManyField(blank=True, to='raumbuch.zutrittsprofil')),
            ],
            options={
                'verbose_name': 'Zutrittstoken',
                'verbose_name_plural': 'Zutrittsgutschriften',
                'ordering': ['mitarbeiter', 'badge_id'],
            },
        ),
    ]
