# Generated by Django 6.0.2 on 2026-03-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raumbuch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zutrittstoken',
            name='status',
            field=models.CharField(choices=[('beantragt', 'Beantragt'), ('aktiv', 'Aktiv'), ('gesperrt', 'Gesperrt'), ('verloren', 'Verloren')], default='aktiv', max_length=20),
        ),
        migrations.CreateModel(
            name='Glasfaserverbindung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('kabel_typ', models.CharField(choices=[('om4', 'OM4 Multimode (bis 100GbE / 400m)'), ('os2', 'OS2 Singlemode (bis 100GbE / 10km)')], default='om4', max_length=10)),
                ('stecker_typ', models.CharField(choices=[('lc_duplex', 'LC Duplex'), ('sc_duplex', 'SC Duplex'), ('mtp_12', 'MTP/MPO 12-faser'), ('mtp_24', 'MTP/MPO 24-faser')], default='lc_duplex', max_length=10)),
                ('fasern_anzahl', models.IntegerField(default=12)),
                ('bandbreite', models.CharField(blank=True, default='10 GbE', max_length=50)),
                ('laenge_m', models.IntegerField(blank=True, null=True, verbose_name='Laenge (m)')),
                ('bemerkung', models.TextField(blank=True)),
                ('nach_raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glasfaser_nach', to='raumbuch.raum')),
                ('von_raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glasfaser_von', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Glasfaserverbindung',
                'verbose_name_plural': 'Glasfaserverbindungen',
            },
        ),
        migrations.CreateModel(
            name='NetzwerkKomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('core_switch', 'Core Switch'), ('distribution_switch', 'Distribution Switch'), ('access_switch', 'Access Switch'), ('patch_panel', 'Patch Panel'), ('glasfaser_verteiler', 'LWL-Verteiler'), ('firewall', 'Firewall / UTM'), ('router', 'Router / WAN'), ('server', 'Server'), ('nas', 'NAS / Storage'), ('ups', 'USV / UPS'), ('kvm', 'KVM-Switch'), ('accesspoint', 'Access Point'), ('sonstiges', 'Sonstiges')], max_length=30)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('hersteller', models.CharField(blank=True, max_length=100)),
                ('modell', models.CharField(blank=True, max_length=100)),
                ('rack_einheit_start', models.IntegerField(blank=True, null=True, verbose_name='Rack-Position (U)')),
                ('rack_einheiten', models.IntegerField(default=1, verbose_name='Hoehe (U)')),
                ('ports_gesamt', models.IntegerField(blank=True, null=True)),
                ('ports_belegt', models.IntegerField(blank=True, null=True)),
                ('ip_adresse', models.CharField(blank=True, max_length=50)),
                ('vlan', models.CharField(blank=True, max_length=100)),
                ('seriennummer', models.CharField(blank=True, max_length=100)),
                ('bemerkung', models.TextField(blank=True)),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='netzwerk_komponenten', to='raumbuch.raum')),
            ],
            options={
                'verbose_name': 'Netzwerk-Komponente',
                'verbose_name_plural': 'Netzwerk-Komponenten',
                'ordering': ['-rack_einheit_start'],
            },
        ),
    ]
