# Generated by Django 6.0.3 on 2026-03-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raumbuch', '0002_netzwerk_komponenten'),
    ]

    operations = [
        migrations.AddField(
            model_name='raumbuchung',
            name='jitsi_link',
            field=models.URLField(blank=True, default='', verbose_name='Jitsi-Meeting-Link'),
        ),
    ]
