# Generated by Django 6.0.3 on 2026-03-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicherheit', '0005_branderkundertoken_since_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branderkundertoken',
            name='status',
            field=models.CharField(choices=[('ausstehend', 'Ausstehend'), ('unterwegs', 'Bin auf dem Weg'), ('am_ort', 'Bin am Brandort'), ('bestaetigt', 'Brand bestaetigt'), ('fehlalarm', 'Kein Brand / Fehlalarm')], default='ausstehend', max_length=20),
        ),
    ]
