# Generated by Django 6.0.1 on 2026-01-21 17:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitszeitvereinbarung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antragsart', models.CharField(choices=[('weiterbewilligung', 'Weiterbewilligung'), ('verringerung', 'Verringerung'), ('erhoehung', 'Erhöhung')], max_length=20)),
                ('arbeitszeit_typ', models.CharField(choices=[('regelmaessig', 'Regelmäßig'), ('individuell', 'Individuelle Wochenverteilung')], max_length=20)),
                ('wochenstunden', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(48)])),
                ('gueltig_ab', models.DateField()),
                ('gueltig_bis', models.DateField(blank=True, null=True)),
                ('telearbeit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('aktiv', 'Aktiv'), ('beendet', 'Beendet')], default='entwurf', max_length=20)),
                ('genehmigt_am', models.DateTimeField(blank=True, null=True)),
                ('beendigung_beantragt', models.BooleanField(default=False)),
                ('beendigung_datum', models.DateField(blank=True, null=True)),
                ('bemerkungen', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genehmigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genehmigte_vereinbarungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arbeitszeitvereinbarung',
                'verbose_name_plural': 'Arbeitszeitvereinbarungen',
                'ordering': ['-gueltig_ab'],
            },
        ),
        migrations.CreateModel(
            name='ArbeitszeitHistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aenderung_am', models.DateTimeField(auto_now_add=True)),
                ('alter_status', models.CharField(choices=[('entwurf', 'Entwurf'), ('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('aktiv', 'Aktiv'), ('beendet', 'Beendet')], max_length=20)),
                ('neuer_status', models.CharField(choices=[('entwurf', 'Entwurf'), ('beantragt', 'Beantragt'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('aktiv', 'Aktiv'), ('beendet', 'Beendet')], max_length=20)),
                ('bemerkung', models.TextField(blank=True)),
                ('aenderung_durch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vereinbarung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historie', to='arbeitszeit.arbeitszeitvereinbarung')),
            ],
            options={
                'verbose_name': 'Arbeitszeithistorie',
                'verbose_name_plural': 'Arbeitszeithistorien',
                'ordering': ['-aenderung_am'],
            },
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalnummer', models.CharField(max_length=20, unique=True)),
                ('nachname', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('abteilung', models.CharField(max_length=100)),
                ('standort', models.CharField(choices=[('siegburg', 'Siegburg'), ('bonn', 'Bonn')], max_length=20)),
                ('eintrittsdatum', models.DateField()),
                ('aktiv', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mitarbeiter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.AddField(
            model_name='arbeitszeitvereinbarung',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbeitszeitvereinbarungen', to='arbeitszeit.mitarbeiter'),
        ),
        migrations.CreateModel(
            name='Tagesarbeitszeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochentag', models.CharField(choices=[('montag', 'Montag'), ('dienstag', 'Dienstag'), ('mittwoch', 'Mittwoch'), ('donnerstag', 'Donnerstag'), ('freitag', 'Freitag'), ('samstag', 'Samstag'), ('sonntag', 'Sonntag')], max_length=15)),
                ('zeitwert', models.IntegerField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(1200)])),
                ('vereinbarung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesarbeitszeiten', to='arbeitszeit.arbeitszeitvereinbarung')),
            ],
            options={
                'verbose_name': 'Tagesarbeitszeit',
                'verbose_name_plural': 'Tagesarbeitszeiten',
                'ordering': ['wochentag'],
                'unique_together': {('vereinbarung', 'wochentag')},
            },
        ),
        migrations.CreateModel(
            name='Urlaubsanspruch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.IntegerField()),
                ('jahresurlaubstage_vollzeit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jahresurlaubstage_anteilig', models.DecimalField(decimal_places=2, max_digits=5)),
                ('genommene_urlaubstage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urlaubsansprueche', to='arbeitszeit.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Urlaubsanspruch',
                'verbose_name_plural': 'Urlaubsansprüche',
                'ordering': ['-jahr'],
                'unique_together': {('mitarbeiter', 'jahr')},
            },
        ),
        migrations.CreateModel(
            name='Zeiterfassung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('arbeitsbeginn', models.TimeField(blank=True, null=True)),
                ('arbeitsende', models.TimeField(blank=True, null=True)),
                ('pause_minuten', models.IntegerField(default=0)),
                ('arbeitszeit_minuten', models.IntegerField(blank=True, null=True)),
                ('art', models.CharField(choices=[('buero', 'Büro'), ('homeoffice', 'Homeoffice/Telearbeit'), ('urlaub', 'Urlaub'), ('krank', 'Krank'), ('sonderurlaub', 'Sonderurlaub')], default='buero', max_length=20)),
                ('bemerkung', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeiterfassungen', to='arbeitszeit.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Zeiterfassung',
                'verbose_name_plural': 'Zeiterfassungen',
                'ordering': ['-datum'],
                'unique_together': {('mitarbeiter', 'datum')},
            },
        ),
    ]
