# Generated by Django 6.0.1 on 2026-01-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='rolle',
            field=models.CharField(choices=[('mitarbeiter', 'Mitarbeiter'), ('sachbearbeiter', 'Sachbearbeiter')], default='mitarbeiter', max_length=20, verbose_name='Rolle'),
        ),
    ]
