# Generated by Django 6.0.1 on 2026-01-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0002_mitarbeiter_rolle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitszeitvereinbarung',
            name='antragsart',
            field=models.CharField(choices=[('weiterbewilligung', 'Weiterbewilligung'), ('verringerung', 'Verringerung'), ('erhoehung', 'Erhöhung'), ('beendigung', 'Beendigung')], max_length=20),
        ),
    ]
