# Generated by Django 6.0.1 on 2026-01-26 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0003_alter_arbeitszeitvereinbarung_antragsart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='arbeitszeit_typ',
            field=models.CharField(blank=True, choices=[('typ_a', 'Typ A - 7:48h'), ('typ_b', 'Typ B - 8:12h'), ('typ_c', 'Typ C - 8:00h'), ('individuell', 'Individuell')], default='typ_c', max_length=20),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='kann_nachtschicht',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='kann_tagschicht',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='max_aufeinanderfolgende_tage',
            field=models.IntegerField(default=5, help_text='Max. Arbeitstage in Folge'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='max_schichten_pro_monat',
            field=models.IntegerField(blank=True, help_text='Begrenzt für Teilzeit', null=True),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='max_wochenenden_pro_monat',
            field=models.IntegerField(default=4, help_text='Maximal X Wochenenden pro Monat'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='nachtschicht_nur_wochenende',
            field=models.BooleanField(default=False, help_text='Nachtschichten nur Fr/Sa/So'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='nur_zusatzarbeiten',
            field=models.BooleanField(default=False, help_text='Nur für Zusatzarbeiten verfügbar (12h)'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='planungs_prioritaet',
            field=models.CharField(blank=True, choices=[('niedrig', 'Niedrig - Flexibel einsetzbar'), ('normal', 'Normal'), ('hoch', 'Hoch - Präferenzen bevorzugt berücksichtigen')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='schichtplan_bemerkungen',
            field=models.TextField(blank=True, help_text='Besondere Hinweise für Schichtplaner'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='schichtplan_kennung',
            field=models.CharField(blank=True, help_text="z.B. 'MA1', 'MA2' - für Excel-Import", max_length=10),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='verfuegbarkeit',
            field=models.CharField(choices=[('voll', 'Vollzeit - alle Schichten'), ('teilzeit', 'Teilzeit - begrenzte Schichten'), ('dauerkrank', 'Dauerkrank - nicht einplanbar'), ('nur_wochenende', 'Nur Wochenende (Fr/Sa/So)'), ('keine_wochenende', 'Keine Wochenenden')], default='voll', max_length=20),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='eintrittsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='rolle',
            field=models.CharField(choices=[('mitarbeiter', 'Mitarbeiter'), ('sachbearbeiter', 'Sachbearbeiter')], default='mitarbeiter', max_length=20),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
