# Generated by Django 6.0.1 on 2026-01-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0004_mitarbeiter_arbeitszeit_typ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitarbeiter',
            name='rolle',
            field=models.CharField(choices=[('mitarbeiter', 'Mitarbeiter'), ('sachbearbeiter', 'Sachbearbeiter'), ('schichtplaner', 'Schichtplaner')], default='mitarbeiter', max_length=20),
        ),
    ]
