# Generated by Django 6.0.1 on 2026-01-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0005_alter_mitarbeiter_rolle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='nur_zusatzdienste_wochentags',
            field=models.BooleanField(default=False, help_text='Mo-Do nur Zusatzarbeiten, keine regulären Schichten', verbose_name='In der Woche nur Zusatzdienste (Z)'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='schichtplan_einschraenkungen',
            field=models.TextField(blank=True, help_text='Freitext für spezielle Wünsche, medizinische Gründe, etc.', verbose_name='Weitere Einschränkungen / Besonderheiten'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='schichtplan_kennung',
            field=models.CharField(blank=True, default='', help_text="z.B. 'MA1', 'MA2' für Excel-Import", max_length=10),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='verfuegbarkeit',
            field=models.CharField(choices=[('voll', 'Vollzeit - alle Schichten'), ('teilzeit', 'Teilzeit - begrenzte Schichten'), ('wochenende_only', 'Nur Wochenende (Fr/Sa/So)'), ('wochentags_only', 'Nur Wochentags (Mo-Do)'), ('dauerkrank', 'Dauerkrank - nicht einplanbar')], default='voll', max_length=20),
        ),
    ]
