# Generated by Django 6.0.1 on 2026-01-28 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0006_mitarbeiter_nur_zusatzdienste_wochentags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagesarbeitszeit',
            options={'verbose_name': 'Tagesarbeitszeit', 'verbose_name_plural': 'Tagesarbeitszeiten'},
        ),
        migrations.AlterUniqueTogether(
            name='tagesarbeitszeit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tagesarbeitszeit',
            name='woche',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tagesarbeitszeit',
            name='wochentag',
            field=models.CharField(choices=[('montag', 'Montag'), ('dienstag', 'Dienstag'), ('mittwoch', 'Mittwoch'), ('donnerstag', 'Donnerstag'), ('freitag', 'Freitag'), ('samstag', 'Samstag'), ('sonntag', 'Sonntag')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tagesarbeitszeit',
            name='zeitwert',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2359)]),
        ),
        migrations.AlterUniqueTogether(
            name='tagesarbeitszeit',
            unique_together={('vereinbarung', 'wochentag', 'woche')},
        ),
    ]
