# Generated by Django 6.0.1 on 2026-01-29 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0007_alter_tagesarbeitszeit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagesarbeitszeit',
            options={'ordering': ['woche', 'wochentag'], 'verbose_name': 'Tagesarbeitszeit', 'verbose_name_plural': 'Tagesarbeitszeiten'},
        ),
    ]
