# Generated by Django 6.0.1 on 2026-01-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0008_alter_tagesarbeitszeit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='schicht_typ',
            field=models.CharField(choices=[('typ_a', 'Typ A - Normale Planung'), ('typ_b', 'Typ B - Min. 4T + 4N pro Monat')], default='typ_a', help_text='Typ A: Normale Planung | Typ B: Mind. 4 Tag- UND 4 Nachtschichten/Monat', max_length=10, verbose_name='Schichttyp'),
        ),
    ]
