# Generated by Django 6.0.1 on 2026-01-31 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0009_mitarbeiter_schicht_typ'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonatlicheArbeitszeitSoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.IntegerField(verbose_name='Jahr')),
                ('monat', models.IntegerField(help_text='1=Januar, 12=Dezember', verbose_name='Monat')),
                ('arbeitstage_gesamt', models.IntegerField(help_text='Alle Werktage (Mo-Fr) im Monat', verbose_name='Arbeitstage gesamt')),
                ('feiertage_anzahl', models.IntegerField(default=0, help_text='Feiertage in NRW, die auf Werktage fallen', verbose_name='Anzahl Feiertage')),
                ('arbeitstage_effektiv', models.IntegerField(help_text='Arbeitstage minus Feiertage', verbose_name='Effektive Arbeitstage')),
                ('wochenstunden', models.DecimalField(decimal_places=2, help_text='Vertragliche Wochenstunden des Mitarbeiters', max_digits=5, verbose_name='Wochenstunden')),
                ('soll_stunden', models.DecimalField(decimal_places=2, help_text='Berechnete Soll-Arbeitsstunden für diesen Monat', max_digits=6, verbose_name='Soll-Stunden')),
                ('feiertage_liste', models.JSONField(blank=True, default=list, help_text='Liste der Feiertage mit Datum und Name', verbose_name='Feiertage')),
                ('berechnet_am', models.DateTimeField(auto_now=True)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monatliche_soll_zeiten', to='arbeitszeit.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Monatliches Arbeitszeitlimit',
                'verbose_name_plural': 'Monatliche Arbeitszeitlimits',
                'ordering': ['jahr', 'monat', 'mitarbeiter'],
                'unique_together': {('mitarbeiter', 'jahr', 'monat')},
            },
        ),
    ]
