# Generated by Django 6.0.1 on 2026-02-05 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0011_mitarbeiter_erlaubte_wochentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='fixe_tag_wochentage',
            field=models.JSONField(blank=True, help_text='JSON: [0-6] für fixe Tagdienste (0=Mo, 6=So). Null = keine fixen Tage. Bsp: MA1=[2] (Mi), MA7=[1,3] (Di,Do)', null=True, verbose_name='Fixe Tagdienst-Wochentage'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='kategorie',
            field=models.CharField(choices=[('kern', 'Kernteam - Reguläre Besetzung'), ('hybrid', 'Hybrid - Teilweise zur Besetzung'), ('zusatz', 'Zusatzkraft - Nicht zur Besetzung'), ('dauerkrank', 'Dauerkrank - Nicht verfügbar')], default='kern', help_text='Bestimmt ob MA zur regulären 2T/2N Besetzung zählt', max_length=20, verbose_name='Mitarbeiter-Kategorie'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='min_nachtschichten_pro_monat',
            field=models.IntegerField(blank=True, help_text='Für Typ B: mindestens 4 Nachtschichten. Leer = keine Mindestanzahl', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Min. Nachtschichten pro Monat'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='min_tagschichten_pro_monat',
            field=models.IntegerField(blank=True, help_text='Für Typ B: mindestens 4 Tagschichten. Leer = keine Mindestanzahl', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Min. Tagschichten pro Monat'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='target_nachtschichten_pro_monat',
            field=models.IntegerField(blank=True, default=5, help_text='Optimales Ziel aus Analyse: 5-6 Nachtdienste/Monat (Soft Constraint)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Ziel Nachtschichten pro Monat'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='target_tagschichten_pro_monat',
            field=models.IntegerField(blank=True, default=6, help_text='Optimales Ziel aus Analyse: 5-6 Tagdienste/Monat (Soft Constraint)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Ziel Tagschichten pro Monat'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='wochenend_nachtdienst_block',
            field=models.BooleanField(default=False, help_text='Wenn aktiv: Nachtdienste am Wochenende immer Fr-Sa oder Sa-So zusammen (typisch für MA7)', verbose_name='Wochenend-Nachtdienste nur als 2er-Block'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='zaehlt_zur_nachtbesetzung',
            field=models.BooleanField(default=True, help_text='False = MA nicht für Nachtdienste eingeplant (z.B. MA1: nur Mittwoch Tag)', verbose_name='Zählt zur Nachtschicht-Besetzung'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='zaehlt_zur_tagbesetzung',
            field=models.BooleanField(default=True, help_text='False = MA ist zusätzlich bei Tagdiensten (z.B. MA7: Di+Do zusätzlich)', verbose_name='Zählt zur Tagschicht-Besetzung'),
        ),
    ]
