# Generated by Django 6.0.2 on 2026-02-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0013_configure_schichtplan_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='verfuegbarkeit',
            field=models.CharField(blank=True, choices=[('voll', 'Vollzeit - alle Schichten'), ('teilzeit', 'Teilzeit - begrenzte Schichten'), ('zusatz', 'Zusatz - nur Zusatzdienste'), ('wochenende_only', 'Nur Wochenende (Fr/Sa/So)'), ('wochentags_only', 'Nur Wochentags (Mo-Do)'), ('dauerkrank', 'Dauerkrank - nicht einplanbar')], default='voll', max_length=20, verbose_name='Verfügbarkeit'),
        ),
    ]
