# Generated by Django 6.0.2 on 2026-02-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0014_mitarbeiter_telefon_alter_mitarbeiter_verfuegbarkeit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arbeitszeitvereinbarung',
            options={'ordering': ['mitarbeiter', 'gueltig_ab', 'versionsnummer'], 'verbose_name': 'Arbeitszeitvereinbarung', 'verbose_name_plural': 'Arbeitszeitvereinbarungen'},
        ),
        migrations.AddField(
            model_name='arbeitszeitvereinbarung',
            name='versionsnummer',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='arbeitszeitvereinbarung',
            name='gueltig_bis',
            field=models.DateField(blank=True, help_text='Nur fuer Payroll-Kommunikation, nicht fuer Versionslogik', null=True),
        ),
    ]
