# Generated by Django 6.0.2 on 2026-02-14 18:31

from django.db import migrations


def versionsnummern_zuweisen(apps, schema_editor):
    """Weist bestehenden Vereinbarungen Versionsnummern zu.

    Pro Mitarbeiter werden alle Vereinbarungen nach gueltig_ab
    sortiert und mit aufsteigenden Versionsnummern versehen.
    """
    Arbeitszeitvereinbarung = apps.get_model(
        "arbeitszeit", "Arbeitszeitvereinbarung"
    )
    Mitarbeiter = apps.get_model("arbeitszeit", "Mitarbeiter")

    for ma in Mitarbeiter.objects.all():
        vereinbarungen = Arbeitszeitvereinbarung.objects.filter(
            mitarbeiter=ma
        ).order_by("gueltig_ab", "pk")
        for nr, v in enumerate(vereinbarungen, start=1):
            if v.versionsnummer != nr:
                v.versionsnummer = nr
                v.save(update_fields=["versionsnummer"])


def rueckwaerts(apps, schema_editor):
    """Setzt alle Versionsnummern auf 1 zurueck."""
    Arbeitszeitvereinbarung = apps.get_model(
        "arbeitszeit", "Arbeitszeitvereinbarung"
    )
    Arbeitszeitvereinbarung.objects.all().update(versionsnummer=1)


class Migration(migrations.Migration):

    dependencies = [
        ("arbeitszeit", "0015_versionsnummer_feld"),
    ]

    operations = [
        migrations.RunPython(
            versionsnummern_zuweisen,
            reverse_code=rueckwaerts,
        ),
    ]
