# Generated by Django 6.0.2 on 2026-02-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0016_versionsnummern_zuweisen'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeiterfassung',
            name='soll_minuten',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeiterfassung',
            name='urlaub_bis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zeiterfassung',
            name='art',
            field=models.CharField(choices=[('homeoffice', 'HomeOffice'), ('telearbeit', 'Telearbeit'), ('krank', 'Krank'), ('urlaub', 'Urlaub'), ('z_ag', 'Z-AG')], default='homeoffice', max_length=20),
        ),
    ]
