# Generated by Django 6.0.2 on 2026-02-14 22:01

from django.db import migrations


def buero_zu_homeoffice(apps, schema_editor):
    """Bestehende Eintraege mit art='buero' auf 'homeoffice' umstellen."""
    Zeiterfassung = apps.get_model("arbeitszeit", "Zeiterfassung")
    Zeiterfassung.objects.filter(art="buero").update(art="homeoffice")


def homeoffice_zu_buero(apps, schema_editor):
    """Rueckwaerts-Migration."""
    Zeiterfassung = apps.get_model("arbeitszeit", "Zeiterfassung")
    Zeiterfassung.objects.filter(art="homeoffice").update(art="buero")


class Migration(migrations.Migration):

    dependencies = [
        ("arbeitszeit", "0017_zeiterfassung_redesign"),
    ]

    operations = [
        migrations.RunPython(
            buero_zu_homeoffice,
            reverse_code=homeoffice_zu_buero,
        ),
    ]
