# Generated by Django 6.0.2 on 2026-02-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0018_zeiterfassung_buero_zu_homeoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeiterfassung',
            name='manuelle_pause',
            field=models.IntegerField(blank=True, help_text='Nur ausfuellen wenn laenger als gesetzliche Pause', null=True, verbose_name='Manuelle Pause (Minuten)'),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='standort',
            field=models.CharField(choices=[('siegburg', 'A'), ('bonn', 'B')], max_length=20),
        ),
        migrations.AlterField(
            model_name='zeiterfassung',
            name='art',
            field=models.CharField(choices=[('homeoffice', 'HomeOffice'), ('telearbeit', 'Telearbeit'), ('hybrid', 'Hybrid (Buero + HomeOffice)'), ('krank', 'Krank'), ('urlaub', 'Urlaub'), ('z_ag', 'Z-AG')], default='homeoffice', max_length=20),
        ),
    ]
