# Generated by Django 6.0.2 on 2026-02-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0019_zeiterfassung_hybrid_manuelle_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeiterfassung',
            name='art',
            field=models.CharField(choices=[('homeoffice', 'HomeOffice'), ('telearbeit', 'Telearbeit'), ('hybrid', 'Hybrid (Buero + HomeOffice)'), ('buero', 'Buero (nur Notiz)'), ('krank', 'Krank'), ('urlaub', 'Urlaub'), ('z_ag', 'Z-AG')], default='homeoffice', max_length=20),
        ),
    ]
