# Generated by Django 6.0.2 on 2026-02-15 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0020_zeiterfassung_art_buero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wochenbericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now=True)),
                ('jahr', models.IntegerField(verbose_name='Jahr')),
                ('kw', models.IntegerField(verbose_name='Kalenderwoche')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wochenberichte', to='arbeitszeit.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Wochenbericht',
                'verbose_name_plural': 'Wochenberichte',
                'ordering': ['-jahr', '-kw'],
                'unique_together': {('mitarbeiter', 'jahr', 'kw')},
            },
        ),
    ]
