# Generated by Django 6.0.2 on 2026-02-15 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0021_wochenbericht'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoKorrektur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemerkung', models.TextField(blank=True)),
                ('datum', models.DateField(verbose_name='Stichtag')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('grund', models.CharField(choices=[('saldovortrag', 'Saldovortrag'), ('kappung', 'Kappung'), ('korrektur', 'Manuelle Korrektur'), ('sonstiges', 'Sonstiges')], default='saldovortrag', max_length=20)),
                ('minuten', models.IntegerField(help_text='Positiv = Gutschrift, negativ = Kappung')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_korrekturen', to='arbeitszeit.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Saldokorrektur',
                'verbose_name_plural': 'Saldokorrekturen',
                'ordering': ['-datum'],
            },
        ),
    ]
