# Generated by Django 6.0.2 on 2026-02-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0022_saldokorrektur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitszeitvereinbarung',
            name='antragsart',
            field=models.CharField(choices=[('ersteinrichtung', 'Ersteinrichtung'), ('weiterbewilligung', 'Weiterbewilligung'), ('verringerung', 'Verringerung'), ('erhoehung', 'Erhöhung'), ('beendigung', 'Beendigung')], max_length=20),
        ),
    ]
