# Generated by Django 6.0.2 on 2026-02-19 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0023_ersteinrichtung_antragsart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monatsbericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now=True)),
                ('jahr', models.IntegerField(verbose_name='Jahr')),
                ('monat', models.IntegerField(verbose_name='Monat')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monatsberichte', to='arbeitszeit.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Monatsbericht',
                'verbose_name_plural': 'Monatsberichte',
                'ordering': ['-jahr', '-monat'],
                'unique_together': {('mitarbeiter', 'jahr', 'monat')},
            },
        ),
    ]
