# Generated by Django 6.0.2 on 2026-02-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0024_monatsbericht'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitarbeiter',
            options={'ordering': ['nachname', 'vorname'], 'permissions': [('view_zeiterfassung', 'Kann Zeiterfassung einsehen'), ('genehmigen_antraege', 'Kann Antraege genehmigen/ablehnen'), ('view_stammdaten', 'Kann Stammdaten einsehen')], 'verbose_name': 'Mitarbeiter', 'verbose_name_plural': 'Mitarbeiter'},
        ),
    ]
