# Generated by Django 6.0.2 on 2026-02-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0025_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='vorgesetzter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direkte_berichte', to='arbeitszeit.mitarbeiter', verbose_name='Vorgesetzter/Vorgesetzte'),
        ),
    ]
