# Generated by Django 6.0.2 on 2026-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitszeit', '0027_standort_komplett'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitszeitvereinbarung',
            name='zyklus_startdatum',
            field=models.DateField(blank=True, help_text='Montag der ersten Woche – nur bei Mehrwochenmodellen', null=True, verbose_name='Startdatum Wochenzyklus'),
        ),
        migrations.AlterField(
            model_name='standort',
            name='kuerzel',
            field=models.CharField(help_text="Internes Kuerzel, z.B. 'siegburg' oder 'berlin'", max_length=20, unique=True, verbose_name='Kuerzel'),
        ),
        migrations.AlterField(
            model_name='standort',
            name='name',
            field=models.CharField(help_text="Anzeigename, z.B. 'Siegburg'", max_length=100, verbose_name='Name'),
        ),
    ]
