# Generated by Django 6.0.2 on 2026-02-19 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arbeitszeit', '0025_init'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BerechtigungsProtokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktion', models.CharField(choices=[('vergeben', 'Vergeben'), ('entzogen', 'Entzogen')], max_length=10, verbose_name='Aktion')),
                ('permission_codename', models.CharField(max_length=100, verbose_name='Berechtigung')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('bemerkung', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('berechtigter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erhaltene_berechtigungen', to=settings.AUTH_USER_MODEL, verbose_name='Berechtigter Nutzer')),
                ('durchgefuehrt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berechtigungs_aktionen', to=settings.AUTH_USER_MODEL, verbose_name='Durchgefuehrt von')),
                ('ziel_mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berechtigungs_protokolle', to='arbeitszeit.mitarbeiter', verbose_name='Betroffener Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Berechtigungsprotokoll',
                'verbose_name_plural': 'Berechtigungsprotokolle',
                'ordering': ['-zeitpunkt'],
            },
        ),
    ]
