# Generated by Django 6.0.2 on 2026-02-23 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hr', '0006_projektgruppe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name des Workflows (z.B. Urlaubsantrag-Genehmigung)', max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, help_text='Was macht dieser Workflow?', verbose_name='Beschreibung')),
                ('kategorie', models.CharField(choices=[('genehmigung', 'Genehmigung'), ('pruefung', 'Pruefung'), ('information', 'Information'), ('bearbeitung', 'Bearbeitung')], default='genehmigung', max_length=50, verbose_name='Kategorie')),
                ('trigger_event', models.CharField(blank=True, help_text='Event das diesen Workflow automatisch startet (z.B. zag_antrag_erstellt)', max_length=100, verbose_name='Trigger-Event')),
                ('ist_aktiv', models.BooleanField(default=True, help_text='Inaktive Templates koennen nicht gestartet werden', verbose_name='Aktiv')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('version', models.IntegerField(default=1, help_text='Version fuer Aenderungsverfolgung', verbose_name='Version')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Workflow-Template',
                'verbose_name_plural': 'Workflow-Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reihenfolge', models.IntegerField(help_text='Position im Workflow (1, 2, 3...)', verbose_name='Reihenfolge')),
                ('titel', models.CharField(help_text='Kurzbeschreibung des Schritts (z.B. Bereichsleiter genehmigt)', max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(blank=True, help_text='Detaillierte Anweisungen fuer den Bearbeiter', verbose_name='Beschreibung')),
                ('aktion_typ', models.CharField(choices=[('genehmigen', 'Genehmigen'), ('pruefen', 'Pruefen'), ('informieren', 'Informieren'), ('bearbeiten', 'Bearbeiten'), ('entscheiden', 'Entscheiden')], default='pruefen', max_length=50, verbose_name='Aktionstyp')),
                ('zustaendig_rolle', models.CharField(choices=[('direkter_vorgesetzter', 'Direkter Vorgesetzter'), ('bereichsleiter', 'Bereichsleiter'), ('geschaeftsfuehrung', 'Geschaeftsfuehrung'), ('hr', 'HR / Personalwesen'), ('controlling', 'Controlling'), ('spezifische_stelle', 'Spezifische Stelle'), ('spezifische_org', 'Spezifische OrgEinheit')], default='direkter_vorgesetzter', max_length=50, verbose_name='Zustaendige Rolle')),
                ('frist_tage', models.IntegerField(default=3, help_text='Tage bis zur Bearbeitung', verbose_name='Frist (Tage)')),
                ('ist_parallel', models.BooleanField(default=False, help_text='Wird gleichzeitig mit naechstem Schritt ausgefuehrt', verbose_name='Parallel')),
                ('bedingung_feld', models.CharField(blank=True, help_text='Feld das geprueft werden soll (z.B. dauer_tage)', max_length=100, verbose_name='Bedingungsfeld')),
                ('bedingung_operator', models.CharField(blank=True, choices=[('>', 'Groesser als'), ('<', 'Kleiner als'), ('==', 'Gleich'), ('!=', 'Ungleich'), ('>=', 'Groesser oder gleich'), ('<=', 'Kleiner oder gleich')], max_length=10, verbose_name='Bedingungsoperator')),
                ('bedingung_wert', models.CharField(blank=True, help_text='Wert zum Vergleichen', max_length=100, verbose_name='Bedingungswert')),
                ('eskalation_nach_tagen', models.IntegerField(default=0, help_text='0 = keine Eskalation', verbose_name='Eskalation nach (Tage)')),
                ('eskalation_an_stelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eskalierte_schritte', to='hr.stelle', verbose_name='Eskalation an Stelle')),
                ('zustaendig_org', models.ForeignKey(blank=True, help_text="Nur bei Rolle 'Spezifische OrgEinheit'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_schritte', to='hr.orgeinheit', verbose_name='Spezifische OrgEinheit')),
                ('zustaendig_stelle', models.ForeignKey(blank=True, help_text="Nur bei Rolle 'Spezifische Stelle'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_schritte', to='hr.stelle', verbose_name='Spezifische Stelle')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritte', to='workflow.workflowtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Workflow-Schritt',
                'verbose_name_plural': 'Workflow-Schritte',
                'ordering': ['template', 'reihenfolge'],
                'unique_together': {('template', 'reihenfolge')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('laufend', 'Laufend'), ('abgeschlossen', 'Abgeschlossen'), ('abgebrochen', 'Abgebrochen'), ('pausiert', 'Pausiert')], default='laufend', max_length=50, verbose_name='Status')),
                ('gestartet_am', models.DateTimeField(auto_now_add=True, verbose_name='Gestartet am')),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('fortschritt', models.IntegerField(default=0, help_text='0-100', verbose_name='Fortschritt (%)')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('gestartet_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestartete_workflow_instanzen', to=settings.AUTH_USER_MODEL, verbose_name='Gestartet von')),
                ('aktueller_schritt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktive_instanzen', to='workflow.workflowstep', verbose_name='Aktueller Schritt')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instanzen', to='workflow.workflowtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Workflow-Instanz',
                'verbose_name_plural': 'Workflow-Instanzen',
                'ordering': ['-gestartet_am'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt'), ('uebersprungen', 'Uebersprungen'), ('eskaliert', 'Eskaliert')], default='offen', max_length=50, verbose_name='Status')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('frist', models.DateTimeField(verbose_name='Frist')),
                ('gestartet_am', models.DateTimeField(blank=True, null=True, verbose_name='Gestartet am')),
                ('erledigt_am', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('entscheidung', models.CharField(blank=True, choices=[('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('weitergeleitet', 'Weitergeleitet'), ('rueckfrage', 'Rueckfrage')], max_length=50, verbose_name='Entscheidung')),
                ('kommentar', models.TextField(blank=True, verbose_name='Kommentar')),
                ('erledigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erledigte_workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflowinstance', verbose_name='Workflow-Instanz')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflowstep', verbose_name='Workflow-Schritt')),
                ('zugewiesen_an_stelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='hr.stelle', verbose_name='Zugewiesen an Stelle')),
                ('zugewiesen_an_user', models.ForeignKey(blank=True, help_text='Falls konkrete Person statt nur Stelle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an User')),
            ],
            options={
                'verbose_name': 'Workflow-Task',
                'verbose_name_plural': 'Workflow-Tasks',
                'ordering': ['frist', '-erstellt_am'],
                'indexes': [models.Index(fields=['zugewiesen_an_stelle', 'status', 'frist'], name='workflow_wo_zugewie_4da2cd_idx'), models.Index(fields=['status', 'frist'], name='workflow_wo_status_abef98_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_wo_content_5cb705_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['status', 'gestartet_am'], name='workflow_wo_status_824408_idx'),
        ),
    ]
