# Generated by Django 6.0.2 on 2026-02-23 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0011_dienstreiseantrag'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='zustaendig_team',
            field=models.ForeignKey(blank=True, help_text="Nur bei Rolle 'Team-Queue' - Team fuer Bearbeitungsstapel", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_schritte', to='formulare.teamqueue', verbose_name='Team-Queue'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='zustaendig_rolle',
            field=models.CharField(choices=[('direkter_vorgesetzter', 'Direkter Vorgesetzter'), ('bereichsleiter', 'Bereichsleiter'), ('geschaeftsfuehrung', 'Geschaeftsfuehrung'), ('hr', 'HR / Personalwesen'), ('controlling', 'Controlling'), ('spezifische_stelle', 'Spezifische Stelle'), ('spezifische_org', 'Spezifische OrgEinheit'), ('team_queue', 'Team-Queue (Bearbeitungsstapel)')], default='direkter_vorgesetzter', max_length=50, verbose_name='Zustaendige Rolle'),
        ),
    ]
