# Generated by Django 6.0.2 on 2026-02-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulare', '0011_dienstreiseantrag'),
        ('hr', '0006_projektgruppe'),
        ('workflow', '0002_workflowstep_zustaendig_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='zugewiesen_an_team',
            field=models.ForeignKey(blank=True, help_text='Entweder Stelle ODER Team-Queue', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='formulare.teamqueue', verbose_name='Zugewiesen an Team-Queue'),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='zugewiesen_an_stelle',
            field=models.ForeignKey(blank=True, help_text='Entweder Stelle ODER Team-Queue', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to='hr.stelle', verbose_name='Zugewiesen an Stelle'),
        ),
    ]
