# Generated by Django 6.0.2 on 2026-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflowtask_zugewiesen_an_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtask',
            name='entscheidung',
            field=models.CharField(blank=True, choices=[('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('weitergeleitet', 'Weitergeleitet'), ('rueckfrage', 'Rueckfrage'), ('zurueck_genehmiger', 'Zurueck an Genehmiger'), ('zurueck_antragsteller', 'Zurueck an Antragsteller')], max_length=50, verbose_name='Entscheidung'),
        ),
    ]
