# Generated by Django 6.0.2 on 2026-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_add_workflow_instance_to_zeitgutschrift'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='edges_data',
            field=models.JSONField(blank=True, help_text='Speichert visuelle Verbindungen zwischen Schritten fuer den Editor', null=True, verbose_name='Verbindungen (Edges)'),
        ),
    ]
