# Generated by Django 6.0.2 on 2026-02-25 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_add_edges_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='auto_config',
            field=models.JSONField(blank=True, help_text='Format je nach aktion_typ:\n- benachrichtigen: {"nachricht": "Text", "user_ids": [1,2,3]}\n- email: {"betreff": "...", "text": "...", "empfaenger": "payroll@firma.de"}\n- webhook: {"url": "https://...", "method": "POST", "data": {...}}\n- python_code: {"code": "print(\'hello\')"}', null=True, verbose_name='Automatische Aktions-Konfiguration'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='schritt_typ',
            field=models.CharField(choices=[('task', 'Benutzer-Task (Standard)'), ('auto', 'Automatische Aktion'), ('decision', 'Entscheidungs-Node (mehrere Ausgaenge)'), ('sync', 'Synchronisations-Point (warten auf alle Eingaenge)')], default='task', max_length=20, verbose_name='Schritt-Typ'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='ist_graph_workflow',
            field=models.BooleanField(default=False, help_text='Wenn True, werden Transitions verwendet statt reihenfolge', verbose_name='Graph-basierter Workflow'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='aktion_typ',
            field=models.CharField(choices=[('genehmigen', 'Genehmigen'), ('pruefen', 'Pruefen'), ('informieren', 'Informieren'), ('bearbeiten', 'Bearbeiten'), ('entscheiden', 'Entscheiden'), ('benachrichtigen', 'Benachrichtigung senden'), ('email', 'Email senden'), ('webhook', 'Webhook aufrufen'), ('python_code', 'Python-Code ausfuehren')], default='pruefen', max_length=50, verbose_name='Aktionstyp'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='reihenfolge',
            field=models.IntegerField(help_text='Position im Workflow (1, 2, 3...) - DEPRECATED: Wird durch Transitions ersetzt', verbose_name='Reihenfolge (Legacy)'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='edges_data',
            field=models.JSONField(blank=True, help_text='DEPRECATED: Wird durch WorkflowTransition ersetzt. Nur fuer Abwaertskompatibilitaet.', null=True, verbose_name='Verbindungen (Edges) - Legacy'),
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedingung_typ', models.CharField(choices=[('immer', 'Immer (keine Bedingung)'), ('entscheidung', 'Basierend auf Task-Entscheidung'), ('feld_wert', 'Basierend auf Feld-Wert'), ('python', 'Custom Python-Code')], default='immer', max_length=20, verbose_name='Bedingungstyp')),
                ('bedingung_entscheidung', models.CharField(blank=True, choices=[('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('weitergeleitet', 'Weitergeleitet'), ('rueckfrage', 'Rueckfrage'), ('zurueck_genehmiger', 'Zurueck an Genehmiger'), ('zurueck_antragsteller', 'Zurueck an Antragsteller')], max_length=30, null=True, verbose_name='Erwartete Entscheidung')),
                ('bedingung_feld', models.CharField(blank=True, max_length=100, verbose_name='Bedingungsfeld')),
                ('bedingung_operator', models.CharField(blank=True, choices=[('==', 'Gleich'), ('!=', 'Ungleich'), ('>', 'Groesser als'), ('<', 'Kleiner als'), ('>=', 'Groesser oder gleich'), ('<=', 'Kleiner oder gleich'), ('in', 'Enthalten in')], max_length=10, verbose_name='Operator')),
                ('bedingung_wert', models.CharField(blank=True, max_length=255, verbose_name='Bedingungswert')),
                ('bedingung_python_code', models.TextField(blank=True, help_text='Python-Code der True/False zurueckgibt. Verfuegbare Variablen: task, instance, content_object', verbose_name='Python-Code')),
                ('label', models.CharField(blank=True, help_text="z.B. 'genehmigt', 'abgelehnt'", max_length=50, verbose_name='Beschriftung fuer Editor')),
                ('prioritaet', models.IntegerField(default=1, help_text='Bei mehreren zutreffenden Transitions', verbose_name='Prioritaet')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowtemplate', verbose_name='Template')),
                ('von_schritt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgaenge', to='workflow.workflowstep', verbose_name='Von Schritt')),
                ('zu_schritt', models.ForeignKey(blank=True, help_text='NULL = Ende-Node', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eingaenge', to='workflow.workflowstep', verbose_name='Zu Schritt')),
            ],
            options={
                'verbose_name': 'Workflow-Uebergang',
                'verbose_name_plural': 'Workflow-Uebergaenge',
                'ordering': ['prioritaet'],
            },
        ),
    ]
