# Generated by Django 6.0.2 on 2026-03-01 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_add_graph_workflow_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtask',
            name='claimed_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Geclaimed am'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='claimed_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Geclaimed von'),
        ),
    ]
