# Generated by Django 6.0.3 on 2026-03-14 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0012_workflow_trigger_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prozessantrag',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Alles was sonst noch wichtig ist', verbose_name='Zusaetzliche Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='aktion_typ',
            field=models.CharField(choices=[('genehmigen', 'Genehmigen'), ('pruefen', 'Pruefen'), ('informieren', 'Informieren'), ('bearbeiten', 'Bearbeiten'), ('entscheiden', 'Entscheiden'), ('benachrichtigen', 'Benachrichtigung senden'), ('email', 'Email senden'), ('webhook', 'Webhook aufrufen'), ('python_code', 'Python-Code ausfuehren'), ('verteilen', 'Verteilen (Postbote)')], default='pruefen', max_length=50, verbose_name='Aktionstyp'),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Was loest dieser Trigger aus?', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Das Model dessen Speichern diesen Trigger ausloest', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Django-Model'),
        ),
        migrations.AlterField(
            model_name='workflowtrigger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
