# Generated by Django 6.0.3 on 2026-03-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_add_workflow_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='ist_laufzettel',
            field=models.BooleanField(default=False, help_text='Dieses Template ist ein gespeicherter Laufzettel (ad-hoc Routing Slip)', verbose_name='Laufzettel-Vorlage'),
        ),
    ]
