# Generated by Django 6.0.3 on 2026-03-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_add_ist_laufzettel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='aktion_typ',
            field=models.CharField(choices=[('genehmigen', 'Genehmigen'), ('pruefen', 'Pruefen'), ('informieren', 'Informieren'), ('bearbeiten', 'Bearbeiten'), ('entscheiden', 'Entscheiden'), ('benachrichtigen', 'Benachrichtigung senden'), ('email', 'Email senden'), ('webhook', 'Webhook aufrufen'), ('python_code', 'Python-Code ausfuehren'), ('verteilen', 'Verteilen (Postbote)'), ('archivieren', 'In DMS-Ablage archivieren'), ('loeschung_freigeben', 'DMS-Loeschung freigeben')], default='pruefen', max_length=50, verbose_name='Aktionstyp'),
        ),
    ]
