# Generated by Django 6.0.2 on 2026-03-07 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentZugriff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True, verbose_name='Zeitpunkt')),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zugriffe', to='dokumente.sensiblesdokument', verbose_name='Dokument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokument_zugriffe', to=settings.AUTH_USER_MODEL, verbose_name='Zugegriffen von')),
            ],
            options={
                'verbose_name': 'Dokument-Zugriff',
                'verbose_name_plural': 'Dokument-Zugriffe',
                'ordering': ['-zeitpunkt'],
            },
        ),
    ]
