# Generated by Django 6.0.3 on 2026-03-22 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntragsPfad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_antragspfade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antrags-Pfad',
                'verbose_name_plural': 'Antrags-Pfade',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AntragsPfadSchritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50, verbose_name='Node-ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('felder_json', models.JSONField(default=list, help_text='Eingabefelder dieses Schritts im Schema-Format', verbose_name='Felder')),
                ('ist_start', models.BooleanField(default=False, verbose_name='Start-Knoten')),
                ('ist_ende', models.BooleanField(default=False, verbose_name='End-Knoten')),
                ('pos_x', models.FloatField(default=200, verbose_name='Position X')),
                ('pos_y', models.FloatField(default=200, verbose_name='Position Y')),
                ('pfad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schritte', to='antraege.antragspfad')),
            ],
            options={
                'verbose_name': 'Antrags-Schritt',
                'verbose_name_plural': 'Antrags-Schritte',
                'ordering': ['pk'],
                'unique_together': {('pfad', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='AntragsPfadSitzung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesammelte_daten', models.JSONField(default=dict, verbose_name='Gesammelte Daten')),
                ('besuchte_schritte', models.JSONField(default=list, verbose_name='Besuchte Schritte')),
                ('status', models.CharField(choices=[('laufend', 'Laufend'), ('abgeschlossen', 'Abgeschlossen'), ('abgebrochen', 'Abgebrochen')], default='laufend', max_length=20)),
                ('gestartet_am', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('aktueller_schritt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktive_sitzungen', to='antraege.antragspfadschritt')),
                ('pfad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sitzungen', to='antraege.antragspfad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antrags_sitzungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antrags-Sitzung',
                'verbose_name_plural': 'Antrags-Sitzungen',
                'ordering': ['-gestartet_am'],
            },
        ),
        migrations.CreateModel(
            name='AntragsPfadTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedingung', models.TextField(blank=True, help_text='Formel-Bedingung (leer = immer wahr). Referenziert Feld-IDs aller bisherigen Schritte.', verbose_name='Bedingung')),
                ('label', models.CharField(blank=True, help_text="Optionaler Text auf der Kante, z.B. 'Ja' oder 'Kampfhund'", max_length=100, verbose_name='Beschriftung')),
                ('reihenfolge', models.IntegerField(default=0, help_text='Auswertungsreihenfolge bei mehreren Ausgaengen (niedrig = zuerst)', verbose_name='Reihenfolge')),
                ('pfad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitionen', to='antraege.antragspfad')),
                ('von_schritt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausgaende', to='antraege.antragspfadschritt', verbose_name='Von')),
                ('zu_schritt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eingaenge', to='antraege.antragspfadschritt', verbose_name='Zu')),
            ],
            options={
                'verbose_name': 'Transition',
                'verbose_name_plural': 'Transitionen',
                'ordering': ['reihenfolge', 'pk'],
            },
        ),
    ]
