# Generated by Django 6.0.3 on 2026-03-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antraege', '0001_initial'),
        ('workflow', '0015_alter_workflowstep_aktion_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='antragspfad',
            name='workflow_template',
            field=models.ForeignKey(blank=True, help_text='Wird nach Pfad-Abschluss automatisch gestartet (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antrags_pfade', to='workflow.workflowtemplate', verbose_name='Workflow starten'),
        ),
        migrations.AddField(
            model_name='antragspfadsitzung',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antrags_sitzungen', to='workflow.workflowinstance', verbose_name='Workflow-Instanz'),
        ),
    ]
